### ISSUE TITLE
`dataall-pipeline-main` CodePipeline timed out 

### ISSUE THREAD

**Issue by antje** [awslabs/aws-dataall#101]
My `dataall-pipeline-main` CodePipeline timed out at the `dataall-<env>-dbmigration-stage` step after 45min (configured timeout). 

How do I proceed? 

And what is it migrating?  This is a fresh install in a new account. Thanks.

```
[Container] 2022/07/24 05:56:48 Running command aws codebuild start-build --project-name dataall-datamesh-dbmigration --profile buildprofile --region us-east-1 > codebuild-id.json
--
13 |  
14 | [Container] 2022/07/24 05:56:49 Running command aws codebuild batch-get-builds --ids $(jq -r .build.id codebuild-id.json) --profile buildprofile --region us-east-1 > codebuild-output.json
15 |  
16 | [Container] 2022/07/24 05:56:49 Running command while [ "$(jq -r .builds[0].buildStatus codebuild-output.json)" != "SUCCEEDED" ] && [ "$(jq -r .builds[0].buildStatus codebuild-output.json)" != "FAILED" ]; do echo "running migration"; aws codebuild batch-get-builds --ids $(jq -r .build.id codebuild-id.json) --profile buildprofile --region us-east-1 > codebuild-output.json; echo "$(jq -r .builds[0].buildStatus codebuild-output.json)"; sleep 5; done
17 | running migration
18 | IN_PROGRESS
19 | running migration
20 | IN_PROGRESS
21 | running migration
22 | IN_PROGRESS
...
```

**Comment by AmineIzanami** [comment]
the `dataall-<env>-dbmigration-stage` step in the pipeline trigger the codebuild project (dataall-datamesh-dbmigration) in the deployment account to run an alembic migration (in case you have changed the DB schema in backend/dataall/db/models)

the timeout can be related to a networking issue , Are you using the same account for tooling and deployment ? are you using an existing VPC ? and can you check the logs of the triggered codebuild project - dataall-datamesh-dbmigration - in the deployment account ?

**Comment by cfregly** [comment]
Same account for tooling and deployment.  Fresh account, so whatever VPC is setup by the installer is what is used.  We did not specify an existing VPC.

I noticed that the alembic pip install is not pinned to a specific version - and the version of alembic changed recently (1.8.x major release).  Not sure if this would cause an issue.  Should this pip install he pinned?

we pasted some of the logs above from the code build project.  Should we paste the full log?  Or what else should we check?

can this step be skipped?  We have a demo coming up later this week - and we don’t have a UI or anything to show.

@AmineIzanami please advise on how we can move forward with the demo.

thanks!

**Comment by AmineIzanami** [comment]
If by fresh account, you mean a fresh AWS Account, you are probably facing a soft limit for the number of concurrent build projects that you can run at once, it is adjustable. You can visit "Service Quotas" Service in your AWS account and request to unlock that soft limit; I believe that should fix your issue.

**Comment by antje** [comment]
I opened a support ticket and asked for a quota increase for AWS CodeBuild `Concurrently running builds`. This solved the issue. Thanks @AmineIzanami !
