### ISSUE TITLE
An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::xxxxxxxxxxx:assumed-role/dataall-sandbox-graphql-role/dataall-sandbox-graphql is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxxxxxxx:role/dataallPivotRole

### ISSUE THREAD

**Issue by JiaTingYefei** [awslabs/aws-dataall#108]
### Describe the bug

An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::xxxxxxxxxxx:assumed-role/dataall-sandbox-graphql-role/dataall-sandbox-graphql is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxxxxxxx:role/dataallPivotRole

I checked all roles in AWS IAM, and there is no arn:aws:iam::xxxxxxxxxxx:role/dataallPivotRole created by CDK 

### How to Reproduce

In the frontend UI, click Organizations -> Link Environment 

### Expected behavior

An environment be created successfully 

### Screenshots

![image](https://user-images.githubusercontent.com/13569268/184792798-3337aad8-207e-4525-be52-1d17d2d585e4.png)

### OS

Linux

### Python version

3.9

### AWS data.all version

v1.0.0

**Comment by dlpzx** [comment]
Related to #148

**Comment by vaquarkhan** [comment]
Same issue found in code , looking #148
