### ISSUE TITLE
SageMaker domain created in environment gets removed with stack updates

### ISSUE THREAD

**Issue by ahom** [awslabs/aws-dataall#111]
### Describe the bug

After creating an Environment with the SageMaker option, subsequent updates to the stack will remove the SageMaker Domain that was created.

### How to Reproduce

Create an environment with SageMaker option.
Trigger an update of the stack through changes unrelated to the SageMaker option.

### Expected behavior

Subsequent stack updates do not remove the SageMaker domain from an Environment unless the option is no longer selected.

### OS

Win

### Python version

3.9

### AWS data.all version

https://github.com/awslabs/aws-dataall/commit/1c0f4f253c536e88d22ca2cd6fa8e0059774dc8b

### Additional context

My understanding is that this fails because of this `if` statement: https://github.com/awslabs/aws-dataall/blob/main/backend/dataall/cdkproxy/stacks/environment.py#L172 
It is `true` at the first deploy then `false` at the second deploy and removes the created SageMaker domain from the stack.

**Comment by dlpzx** [comment]
Solved in PR #157
