### ISSUE TITLE
Environment group role is missing permissions for working with worksheet 

### ISSUE THREAD

**Issue by degoldner** [awslabs/aws-dataall#115]
### Describe the bug

When the group/team does **not have the permission to to create datasets within this environment** it **cannot query shared datasets with the workshee**t as **IAM permissions are missing** for the associated group role.

### How to Reproduce

Create a team which does not have permissions to create a datasets in the environment. Create a share request to an existing dataset created by another persona with permissions. Try to query a table in this dataset from a worksheet.

### Expected behavior

The dataset table should be queriable without the need to have the create dataset permission for the acting group/team.

### Screenshots

![image](https://user-images.githubusercontent.com/107395339/186164886-0037c031-75d0-4461-8d5b-7973212b75d6.png)

### OS

Deployed to AWS

### Python version

3.9

### AWS data.all version

https://github.com/awslabs/aws-dataall/commit/7300220b4842247739d3fea0de2747498180dc14

**Comment by dlpzx** [comment]
Solved in linked PR
