### ISSUE TITLE
Error "can't find valid container" that is ocasionally when trying to access dashboards

### ISSUE THREAD

**Issue by louishourcade** [awslabs/aws-dataall#121]
### Describe the bug

A customer raised this issue when accessing its dashboard. Sometimes, an error message appear "can't find valid container".

### How to Reproduce

Create some dashboards in data.all, and see if the error appears.

### Expected behavior

No error message should be raised.

### OS

Llinux

### Python version

3.10

### AWS data.all version

1.0.0

**Comment by mvidhu** [comment]
We have also noticed this issue for one user.

**Comment by dlpzx** [comment]
Hi @mvidhu can you provide more info? In which UI view does it appear?
Do you have any screenshots?

Let's see if we can solve it

**Comment by mvidhu** [comment]
> Hi @mvidhu can you provide more info? In which UI view does it appear? Do you have any screenshots?
> 
> Let's see if we can solve it

We see the error in dashboard UI. Dashboard List View. I will ask user to provide screenshot.I don't get the error when I access.

**Comment by mvidhu** [comment]
> > Hi @mvidhu can you provide more info? In which UI view does it appear? Do you have any screenshots?
> > Let's see if we can solve it
> 
> We see the error in dashboard UI. Dashboard List View. I will ask user to provide screenshot.I don't get the error when I access.

![Uploading image.png…]()

**Comment by dlpzx** [comment]
I was also able to reproduce the error, although it appears in the console it does not seem to affect the functionality
