### ISSUE TITLE
Inconsistency when filtering results by type in the Catalog

### ISSUE THREAD

**Issue by louishourcade** [awslabs/aws-dataall#123]
### Describe the bug

A customer raised this issue with the Catalog. When they filter the catalog items based on the type, they get an inconsistent behavior. Sometimes, all items are displayed, even if they filter on a specific resource type ("dashboard" for example)

### How to Reproduce

Create resources with multiple types in dataall. Then, try to filter resources by type in the Catalog view. Check that the results are consistent.

### Expected behavior

The result of the query should be consistent, and should show only times of the selected types.

### OS

Linux

### Python version

3.10

### AWS data.all version

1.0.0

**Comment by dlpzx** [comment]
Unfortunately I have been trying to re-create this issue but it seems to work just fine with the current code:

Filtering by folders (only 7 in this platform)
![image](https://user-images.githubusercontent.com/71252798/188590096-c6be02de-f7e0-4bff-aa24-4aee4885ac5c.png)
 Filtering by dahsboard (only 4)
![image](https://user-images.githubusercontent.com/71252798/188590362-ef06d7e5-5a5b-4f8b-aa11-515d3cc5b1b5.png)
 Same applies for tables and datasets.

Maybe what they refer to is the number of items that is displayed in the different filtering categories. For example here, although there are only 4 dashboards it shows a number of 130 unclassified items, 15 secret and 6 official (all data items)
![image](https://user-images.githubusercontent.com/71252798/188590947-7a6e33de-8950-44d5-bc5b-cce5cac36d86.png)
