### ISSUE TITLE
Search funtionality for Pipeline & Dashboard resources in Data.all not working when used from specific pages

### ISSUE THREAD

**Issue by louishourcade** [awslabs/aws-dataall#124]
### Describe the bug

This issue was raised by a customer. The "Dashboards" and "Pipelines" menus both offer a search functionality. You can have multiple pipelines and dashboards, which results in having your resources displayed in multiple pages.
If you have 5 pages of pipelines, then using the search bar from the 5th page might show en empty result from the user (unless the user comes back to page 1 after making the search). Same thing for Dashboards.

### How to Reproduce

Create many Pipelines in your data.all instance. Ideally, you need to have multiple pages of these resources (3 or 4). Then, go to the last page, and use the search bar to look for specific pipelines. This is likely to result in an empty search, unless you go back to page 1.
Same think with Dashboards.

### Expected behavior

If there results that match, the search bar should not return empty results to the user (Pipeline and Dashboards)

### OS

Linux

### Python version

3.10

### AWS data.all version

1.0.0

**Comment by dlpzx** [comment]
It also affects the lists of Environments, Organizations... basically anything that is listed.
