### ISSUE TITLE
Linking environment error - An error occurred (AccessDenied) when calling the AssumeRole operation (graphql)

### ISSUE THREAD

**Issue by gavclark** [awslabs/aws-dataall#143]
I'm trying to create a new environment in data all (first time I've tried, so it could be I've missed something) . I have 3 accounts as below:

Tooling account: 000000007632
Deployment account: 000000007481
Environment account: 000000004543

I completed the pre-requisite steps:
- bootstrapped the environment account from the deployment/infrastructure account (cdk bootstrap --trust 00000007481 -c @aws-cdk/core:newStyleStackSynthesis=true --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess aws://000000004543/eu-west-1
- created the dataallPivotRole using the yaml template provided (in the deployment account and the environment account)

When I try and link an environment, I get the following error:
![image](https://user-images.githubusercontent.com/16735754/191964750-e3f0c9a2-f692-4201-9ae3-9707f844ee55.png)

Error message as text: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::000000007481:assumed-role/dall-depl7481-graphql-role/dall-depl7481-graphql is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::000000004543:role/dataallPivotRole

I'm not really sure if this is a bug or is something I've missed. As far as I can tell, I've followed the steps in the documentation provided.

**Comment by dlpzx** [comment]
Hi @gavclark, the account that you introduce as parameter to the pivot role CloudFormation template should be the deployment account: 000000007481. It is the account that is trusted in the Pivot role IAM role trust relationship. Let us change the template so that it is clearer. Right now it might be a bit misleading.

Let us know if you find other issues
