### ISSUE TITLE
Add support to run any specific task from other task based on some condition.

### ISSUE THREAD

**Issue by pravinbandivadekar** [awslabs/aws-dataall#155]
To overcome timeout limitation of 15 min for lambda we want to design our step function with lambda task to call other task in cyclic manner to check execution status based on some condition.
	
	Please refer attached snapshot for our use case with step function using lambda tasks.
	
	1. RunQuery is lambda to trigger redshift query and which provides output parameter "Id" for redshift data API .
	2. GetQueryStatus is another lambda which will read "Id" parameters and get the status of redshift query. Provide status as output parameter.
	3. CheckQuerySTatus is choice type in step function. Following is logic to trigger corresponding state based on choice:
		a. If Status is FINISHED, end step function with success.
		b. If Status is FAILED, end step function with failure.
		c. If status is not FINISHED or FAILED, call GetQueryStatus and again get status of query.
		
	P.N. Attached step function has parallel branches one for Venue table and Event table. Please consider above use case for any of the table.
	
	In current data.all architecture cyclic execution of job based on condition is not supported. Currently all jobs mentioned in groups from config.yaml will execute one task after another task in sequence. 
	Adding support for cyclic task execution would enhance data.all to have more flexiblity.
<img width="575" alt="parallel_lambda" src="https://user-images.githubusercontent.com/16334380/194303760-eeaccadb-c9a7-43c9-8bbb-11a617dd49c3.PNG">

**Comment by dlpzx** [comment]
Hello @pravinbandivadekar, welcome to the project!
I think you are referring to the pipeline blueprint right? The purpose of the blueprint was to speed up data pipeline definition by providing a wrapper on top of step functions. Blueprints were written on CDK v1 and as you mentioned in the enhancement, they were limited to an specific type of step function (and glue jobs in the handlers). For these reasons, blueprints have been replaced by AWS DDK applications. AWS DDK is a project that also provides an abstraction layer on top of data pipelines to allow data engineers to focus on transformation code.

We are currently working on a multi-environment implementation of the AWS DDK application to simplify cross-account development of data pipelines. Check out #77
