### ISSUE TITLE
Check for VPC completeness when deploying with specific vpc id.

### ISSUE THREAD

**Issue by chachadsaws** [awslabs/aws-dataall#178]
### Describe the bug

In cdk.json while working with existing vpc_id check for completeness of the VPC. Deploying to default VPC which does not have any private subnets fails to synth in the VpcStack._create_vpc_endpoints. The error that is displayed is generic: **RuntimeError: Error: Can't add a gateway endpoint to VPC; route table IDs are not available**

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
Start from new AWS account with default VPC.
Pull code. 
Update cdk.json to specify default vpc_id for tooling and dev environment accounts
run cdk synth
Error is displayed.

### Expected behavior

If VpcStack if vpc_id is passed and vpc is pulled using from_lookup, check to verify that if there is at least 1 private subnet. If not then give appropriate error to indicate and stop. For e.g., "Private subnet not found in specified VPC. Data.all requires at least 1 private subnet.".
And/Or
Update documentation to indicate that requirement. 

### OS

Mac

### Python version

3.8

### AWS data.all version

v1.1.2

**Comment by dlpzx** [comment]
I think this is a nice idea. Although it is documented in the architecture what is the VPC architecture needed, it is true that users instinctively use default one. 

<img width="1452" alt="image" src="https://user-images.githubusercontent.com/71252798/198205463-d5b8a832-ada1-457e-a8f2-5c1ec40fd33a.png">

"data.all creates its own VPC in the account where it is set up, with usual configuration. All compute is hosted in the private subnets, and communicates with AWS Services through a NAT Gateway.

All data.all Lambda functions and ECS tasks are running inside this VPC and in private subnets."

In any case, resources are deployed in private subnets so it seems reasonable that customers provide those (if they don't allow data.all to create a VPC)

https://awslabs.github.io/aws-dataall/architecture/
