### ISSUE TITLE
Allow adding custom tags

### ISSUE THREAD

**Issue by josepulv82** [awslabs/aws-dataall#179]
A good practice in AWS is to have a proper tagging strategy. Therefore, it is good to be able to add custom tags to resources.

One suggestion be to use a file where we can add the tags according to our strategy and the cdk code could add them dynamically.

**Comment by dlpzx** [comment]
Hi @josepulv82 welcome to data.all! 
This feature is already implemented. For all the data.all objects that also deploy a CDK stack users can add their custom tags in the "Tags" tab. For example, here I am adding a project tag to a dataset stack:
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/71252798/198519441-ddaf143b-7966-4487-a0c1-e6a746219505.png">

**Comment by WorkplaceCowboy** [comment]
When instantiating the data.all resources like IAM roles, Cognito, API Gateways, etc. are there provisions to apply baseline tagging to those resources?

**Comment by dlpzx** [comment]
Hi @WorkplaceCowboy, welcome to the project. Let's differentiate between the data.all infrastructure resources and the environments/datasets/pipelines... stacks that get deployed in the environment accounts:

- For the infrastructure of data.all (Cognito, API Gateway, Lambdas, ECS...) all resources are tagged with the key-calue tag:Tags.of(self).add('Application', f'{resource_prefix}-{git_branch}')
