### ISSUE TITLE
Support Cognito identity providers

### ISSUE THREAD

**Issue by josepulv82** [awslabs/aws-dataall#180]
the solution at this time supports the use of a local user pool.

Companies often have a solution that is in charge of the users who are allowed to use their applications, so it would be great to have the ability to add the idp feature to the existing Cognito feature so we can choose a SAML integration in Cognito for example.

**Comment by dlpzx** [comment]
Hi @josepulv82, you are totally right, customers often have other identity providers. In several projects we have integrated Cognito with those Idps; we don't do it from the data.all UI or the deployment, but as an after-step when the platform is deployed. 

For example, one typical integration is with Azure AD, check this discussion #68.
We have developed a few guides on the most frequent integrations, so maybe this is our chance to collect those :) In general, what we need to keep in mind are the mappings between the identity providers.

**Comment by josepulv82** [comment]
Hi @dlpzx , thanks for your answer, we are interested in the SAML integration with Google.

**Comment by dlpzx** [comment]
Hi @josepulv82, for Google the integration is slightly different. Here are some useful resources that might help you:
- https://aws.amazon.com/premiumsupport/knowledge-center/cognito-google-social-identity-provider/ 
- https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-social-idp.html

The steps explained in #68 are also applicable in this case:
1. Get the ACS endpoint and the Entity ID from AWS Cognito
2. Create an Google application and set up the application to login the Cognito origins (Create a Google API Console project, Configure the OAuth consent screen and Get OAuth 2.0 client credentials in  https://aws.amazon.com/premiumsupport/knowledge-center/cognito-google-social-identity-provider/ )
3. Configure Google as federated IdP in Cognito
4. Attribute Mapping ---> IMPORTANT!!! You need to add saml.groups as custom attribute!
5. Enable the IdP in the App Client Settings

I will attach the Azure guide here again as reference. The only non-standard step in the Attribute mapping section, which includes a custom attribute particular to data.all
[Azure+Active+Directory+Integration+with+Amazon Cognito+User+Pools.pdf](https://github.com/awslabs/aws-dataall/files/9949390/Azure%2BActive%2BDirectory%2BIntegration%2Bwith%2BAmazon.Cognito%2BUser%2BPools.pdf)

Let us know if you need any further help!
