### ISSUE TITLE
Update UI to make it clear that tags are related to the Stack and not the resource

### ISSUE THREAD

**Issue by gavclark** [awslabs/aws-dataall#193]
**Is your idea related to a problem? Please describe.**
When maintaining tags in data.all UI for a resource (e.g., pipeline) , it is not immediately obvious that you are actually maintaining the tags for the CloudFormation stack.

**Describe the solution you'd like**
Possibly have some title in the tag maintenance screen that says it is Stack tags, or change the text of the button to say "Add/Edit Stack Tags"

![image](https://user-images.githubusercontent.com/16735754/200170790-ebe41ed3-517e-4f61-99da-6486fe116340.png)

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by dlpzx** [comment]
Sure this is an easy enhancement, I will pick it up. Thanks for the feedback

**Comment by dlpzx** [comment]
Included in next release v1.3.0
