### ISSUE TITLE
Apply pipeline stack key-value tags to all data pipeline resources

### ISSUE THREAD

**Issue by gavclark** [awslabs/aws-dataall#195]
### Describe the bug

When a pipeline is created in data.all a number of additional resources are also created. 

When tags are applied to the stack via the data.all UI and the stack is updated, the majority of the associated stack resources are updated with the tags.

This doesn't appear to be the case with Step Functions - the tags are not updated at all. 

The Step Function doesn't appear to be in the CloudFormation stack and is perhaps created via the build and deploy of the code pipeline?

### How to Reproduce

Create a pipeline in data.all UI and add some tags:
![image](https://user-images.githubusercontent.com/16735754/200172978-de94977a-df9c-4f11-a349-a8ea5b03bca4.png)

Once the stack update has completed, locate the Step Function related to this pipeline (searched using the pipeline resourceUri:
![image](https://user-images.githubusercontent.com/16735754/200173065-7ba7e42c-bb9b-46bc-972f-c3f18116a17a.png)

Check the Step Function tags:

The additional tags maintained for the pipeline stack don't appear.

### Expected behavior

If the stack creates objects (or triggers the creation of objects in build/deploy) , it should also update them, including tags.

### Your project

n/a

### OS

n/a

### Python version

3.8

### AWS data.all version

1.0

**Comment by dlpzx** [comment]
Hi @gavclark, I worked with your version of data.all (is the one creating a Step Function from a yaml file right?)
In the new versions the blueprint has be replaced by an AWS DDK application.

In any case the stack deployed from data.all is just a CICD pipeline (so tags apply to this stack). Depending on the definition of the DDK app or of your yaml file different resources are deployed  from the CICD pipeline to build the data pipeline.

In the DDK app version we add some by-default tags (which does not include key-value tags) to the resources, but this seems to not be the case for previous versions. 

Conclusion:
- From our side we can work on passing all key-value tags to the DDK application in the open-source version. It would be an enhancement feature)
- If you still want to keep working with the previous blueprints, you can modify the code to add tags to the stacks created by the CICD pipeline.

**Comment by gavclark** [comment]
Hi @dlpzx , sorry I've only got around to replying to this now ! 

Yes, we create the Step Function from a YAML file - for how much longer should we keep doing that (or , when should we start using the DDK)

I'm still not 100% sure whether your suggestion would work for us (modifying the code to add tags to the stacks created by CICD pipeline) . Is there an option to have a call please ?

**Comment by dlpzx** [comment]
Hi @gavclark, I will reach out to the corresponding Professional Services team to organize a call. But in general, from the open-source team we focus on developing the last version of the code, therefore when considering tagging of resources it will be on the current implementation of pipelines. 

If you want to implement tagging in your code with the previous blueprint, my advice is to go an find in the app.py of the blueprint and add CDK Tags: `Tags.of(app).add("dataall", "true")
Tags.of(app).add("Target", pipeline_name))` . This is basically what we are doing in the DDK pipelines
