### ISSUE TITLE
View Table Partition Key in UI

### ISSUE THREAD

**Issue by chamiles** [awslabs/aws-dataall#208]
As a engineer,
      I would like to create the ability to enable the partition key for table available in the UI so that end users who are building datasets from producers to simplify knowledge of the data.

**Comment by dlpzx** [comment]
Hi @chamiles, at the moment we do not have capacity for implementing this feature. But it does not seem too complicated to implement in data.all. Information about columns is retrieved from Glue catalog and written into a particular table in RDS.
What we need to do is to modify the API call that reads this information and add the partition key information as a new filed for each "Table column". PartittionKey = True/False. Or as generic information of the "Table" PartitionKey = Column1

**Comment by anmolsgandhi** [comment]
Closing this issue as there has been no update, feel free to reopen if its still a requirement.
