### ISSUE TITLE
After deploying on AWS, how do we access the front end?

### ISSUE THREAD

**Issue by mariandumitrascu** [awslabs/aws-dataall#21]
*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*
After deploying on AWS, how do we access the front end, the application?
I coudnt find any indications about how to access the app after being deployed on AWS. 

Thank you,
-Marian

**Comment by mariandumitrascu** [comment]
Sorry. Nevermind. I found the link in us-east-1 CFT output.  First users needs to be created in cognito

**Comment by dlpzx** [comment]
Welcome to the project Marian. We will make sure to clarify the documentation.
