### ISSUE TITLE
CDK Pipeline assets build fails 

### ISSUE THREAD

**Issue by gavclark** [awslabs/aws-dataall#210]
### Describe the bug

Changed the code in "backend/dataall/cdkproxy/stacks/dataset.py" to change the bucket versioning behaviour to be "false" by default (line 244) , see screenshot

![image](https://user-images.githubusercontent.com/16735754/202026222-49e75a41-d076-4433-9502-a3d34565ac12.png)

Updated code was then pushed back to repo and the code build started , it then failed
![image](https://user-images.githubusercontent.com/16735754/202026590-26cd47f8-250b-4233-9424-b7a1cdd56409.png)

Tried reversing code change and rebuilding but still fails with the same issue , here's an excerpt from the build log:

/usr/local/bin/cdk-assets -> /usr/local/lib/node_modules/cdk-assets/bin/cdk-assets
/usr/local/bin/docker-credential-cdk-assets -> /usr/local/lib/node_modules/cdk-assets/bin/docker-credential-cdk-assets
+ cdk-assets@2.50.0
added 129 packages from 105 contributors in 6.589s

[Container] 2022/11/09 14:32:48 Phase complete: INSTALL State: SUCCEEDED
[Container] 2022/11/09 14:32:48 Phase context status code:  Message: 
[Container] 2022/11/09 14:32:48 Entering phase PRE_BUILD
[Container] 2022/11/09 14:32:48 Phase complete: PRE_BUILD State: SUCCEEDED
[Container] 2022/11/09 14:32:48 Phase context status code:  Message: 
[Container] 2022/11/09 14:32:48 Entering phase BUILD
[Container] 2022/11/09 14:32:48 Running command cdk-assets --path "assembly-dataall-dev-cicd-stack-dataall-dev-backend-stage/dataalldevcicdstackdataalldevbackendstagebackendstackC936AB86.assets.json" --verbose publish "bdb08b9984816ecf43301a0c6d8913e270ee2448940b6b95e430dd222a4d90be:123456789012-eu-west-1"
verbose: Loaded manifest from assembly-dataall-dev-cicd-stack-dataall-dev-backend-stage/dataalldevcicdstackdataalldevbackendstagebackendstackC936AB86.assets.json: 23 assets found
verbose: Applied selection: 1 assets selected.
info   : [0%] start: Building and publishing bdb08b9984816ecf43301a0c6d8913e270ee2448940b6b95e430dd222a4d90be:123456789012-eu-west-1
verbose: [0%] check: Check s3://cdk-hnb659fds-assets-123456789012-eu-west-1/bdb08b9984816ecf43301a0c6d8913e270ee2448940b6b95e430dd222a4d90be.zip
error  : [100%] fail: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
Failure: CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
    at Request.extractError (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/sequential_executor.js:116:18)

[Container] 2022/11/09 14:32:48 Command did not exit successfully cdk-assets --path "assembly-dataall-dev-cicd-stack-dataall-dev-backend-stage/dataalldevcicdstackdataalldevbackendstagebackendstackC936AB86.assets.json" --verbose publish "bdb08b9984816ecf43301a0c6d8913e270ee2448940b6b95e430dd222a4d90be:123456789012-eu-west-1" exit status 1
[Container] 2022/11/09 14:32:48 Phase complete: BUILD State: FAILED
[Container] 2022/11/09 14:32:48 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cdk-assets --path "assembly-dataall-dev-cicd-stack-dataall-dev-backend-stage/dataalldevcicdstackdataalldevbackendstagebackendstackC936AB86.assets.json" --verbose publish "bdb08b9984816ecf43301a0c6d8913e270ee2448940b6b95e430dd222a4d90be:123456789012-eu-west-1". Reason: exit status 1
[Container] 2022/11/09 14:32:48 Entering phase POST_BUILD
[Container] 2022/11/09 14:32:48 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2022/11/09 14:32:48 Phase context status code:  Message: 

I am not sure if it really is missing credentials ? those weren't changed - only the code was updated. This happened about 6 months ago when we were first implementing this version and @louishourcade helped resolve it while he was working on the project.

### How to Reproduce

Changed code, committed and pushed changes - code build fails

### Expected behavior

codebuild project completed successfully

### Your project

n/a

### OS

n/a

### Python version

3.7

### AWS data.all version

1.0

**Comment by dlpzx** [comment]
Hello @gavclark, does this happen with any change that you apply on the pipeline? Also, if you just release a change with no modifications of the code, does the error persist?

**Comment by xavierxc14** [comment]
Hi @gavclark this happens on a cross-account deployment when codebuild (in the source account) tries to upload assets into the cdk assets bucket in another account.
To fix this issue, the target account should be properly bootstrapped with the command:
cdk bootstrap --trust <source-account-id> -c @aws-cdk/core:newStyleStackSynthesis=true --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess aws:// <deployment-account-id>/<aws-region>

**Comment by dlpzx** [comment]
Thank you @xavierxc14!
