### ISSUE TITLE
Tagging of glue / lambda resources for a pipeline (related to #195)

### ISSUE THREAD

**Issue by gavclark** [awslabs/aws-dataall#211]
This is related to #195 

When the team are developing glue jobs, lambda functions etc. related to the "parent stack" of the pipeline, what is the best way to apply key-value tags (e.g. for cost allocation) to these resources ? . 

We have applied them via tag editor, but it seems that when the CICD process runs, these tags are removed again.

Do we need to apply the tags in a different way to ensure they are persisted against the glue job or lambda and not removed ?

**Comment by dlpzx** [comment]
I am going to close this issue to keep talking in the #195 as it is basically the same issue.
