### ISSUE TITLE
Change tenant permissions screen to be more specific

### ISSUE THREAD

**Issue by gavclark** [awslabs/aws-dataall#215]
**Is your idea related to a problem? Please describe.**
When setting up a team permissions in data.all, there are two options displayed for "Manage pipelines"

![image](https://user-images.githubusercontent.com/16735754/202654560-773dbf39-d676-4236-b780-80a4c2839f67.png)

it is not clear whether this is a duplicated entry or should one of them be renamed to make it clear what kind of pipelines it relates to?

**Describe the solution you'd like**
Removal of the duplicated entry for "Manage pipelines" or make it clear which kind of pipelines if there is a difference

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by dlpzx** [comment]
I think this is a bug more than an enhancement. I just changed the label and I will fix it in the associated branch. Thanks for reporting!
