### ISSUE TITLE
Pipeline Type to filter results on pipeline role role and list view

### ISSUE THREAD

**Issue by chamiles** [awslabs/aws-dataall#219]
Currently pipelines are just listed in no specific order, the customer would like to be able to filter pipelines based on a tag or filter type of the pipeline. ability to have list view for end users that have thousands of pipelines it would be easier to look through.

**Describe the solution you'd like**
Ability when creating or editing a pipeline to attach a pipeline type (Ingestion, Use-Case, Transform, etc) and filter based on type

**Comment by dlpzx** [comment]
@chamiles this feature has been included for the next release v1.4.0 and is currently being reviewed
