### ISSUE TITLE
Failed to query shared dataset due to incorrect table names in SQL Worksheets

### ISSUE THREAD

**Issue by aaronchong888** [awslabs/aws-dataall#241]
### Describe the bug

When a data consumer has been granted access to a shared dataset, the number of databases showed in SQL Worksheet is incorrect, and the NAME of the database table is also incorrect.

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
1. Request for a dataset from another environment
2. Got approval to use the dataset
3. Use Worksheet feature to query the shared dataset
4. The number of databases showed is incorrect, and the names of database are inconsistent with Athena & Glue Data Catalog

### Expected behavior

It should only show the authorized databases, and display the correct database names within Worksheets.

### Screenshots

**SYNTAX_ERROR: line 1:15: Schema datascience_marketing_dataset_tgwr16m9shared does not exist** due to incorrect database name displayed & used in data.all Worksheet
![Screenshot 2022-12-02 at 2 41 02 PM](https://user-images.githubusercontent.com/8871864/206135291-91cb2228-44e8-4497-a404-1544dda1cfdf.png)

The correct database names should be the ones in Athena console below (data.all Worksheet is inconsistent with Athena):
![Screenshot 2022-12-02 at 2 38 08 PM](https://user-images.githubusercontent.com/8871864/206135401-82087750-6eaa-4c4f-a51d-a489dabe8423.png)

The correct database name in Athena Console should be - datascience_marketing_dataset_tgwr16m9 **_shared_ylhuw70y**, but the one showed on data.all is datascience_marketing_dataset_tgwr16m9**shared**
![Screenshot 2022-12-02 at 2 45 35 PM](https://user-images.githubusercontent.com/8871864/206135369-bd067c2b-3095-4275-b3ca-c5eb69bb8f1c.png)

### OS

AWS Deployment

### Python version

3.8

### AWS data.all version

1.2.2

**Comment by noah-paige** [comment]
Thank you for calling this out - the correct Glue Database name for the shared resource should be fixed with this recent PR and only the shared db name will be present in the list(https://github.com/awslabs/aws-dataall/pull/244)
