### ISSUE TITLE
cdk deploy fails when using us-west-1

### ISSUE THREAD

**Issue by zsaltys** [awslabs/aws-dataall#261]
### Describe the bug

cdk deploy fails when using us-west-1 because CodeArtifact is not supported by CDK in us-west-1

### How to Reproduce

configure cdk.json to use us-west-1 as the tooling region

### Expected behavior

I can't tell if it can be fixed without fixing CDK itself but perhaps an install documentation update can be made to tell users not to use us-west-1.

### OS

Mac

### Python version

3.8

### AWS data.all version

v1.2.3

**Comment by dlpzx** [comment]
Taking a look at this issue. If necessary I will update the documentation. Thank you @zsaltys!!

**Comment by dlpzx** [comment]
I am adding this info to the docs, but for future reference, this issue appears for any region where CodeArtifact is not available:
https://aws.amazon.com/codeartifact/faq/
