### ISSUE TITLE
codebuild "Build" step fails due to pyenv issue

### ISSUE THREAD

**Issue by zsaltys** [awslabs/aws-dataall#262]
### Describe the bug

When Build runs all AWS commands fail because AWS cli cannot be resolved. There is a notice from pyenv that "Python 3.8 is not installed". .python-versions was set to 3.8. However on the container itself the installed python version is 3.8.13. I don't know why but the "Build" environment does not pick up the Python version for pyenv local 3.8.13. I fixed this issue by adding pyenv local 3.8.13 to the buildspec.

### How to Reproduce

Trigger the default CodeBuild pipeline following install documentation. It should fail with Python 3.8 issue.

### Expected behavior

CodeBuild pipeline works.

### OS

Linux

### Python version

3.8

### AWS data.all version

v1.2.3

**Comment by zsaltys** [comment]
Here's an example where it fails in later steps as well:

```
[Container] 2022/12/19 18:14:39 going inside waitForAgent



[Container] 2022/12/19 18:14:39 Waiting for agent ping



[Container] 2022/12/19 18:14:40 Waiting for DOWNLOAD_SOURCE



[Container] 2022/12/19 18:14:42 Phase is DOWNLOAD_SOURCE



[Container] 2022/12/19 18:14:42 finished waitForAgent



[Container] 2022/12/19 18:14:42 CODEBUILD_SRC_DIR=/codebuild/output/src981310543/src



[Container] 2022/12/19 18:14:42 YAML location is /codebuild/readonly/buildspec.yml



[Container] 2022/12/19 18:14:42 Setting HTTP client timeout to higher timeout for S3 source



[Container] 2022/12/19 18:14:42 Processing environment variables



[Container] 2022/12/19 18:14:42 No runtime version selected in buildspec.



[Container] 2022/12/19 18:14:44 Moving to directory /codebuild/output/src981310543/src



[Container] 2022/12/19 18:14:44 Configuring ssm agent with target id: codebuild:c01a8ec7-ab7c-4d8b-b67e-17dabfb54202



[Container] 2022/12/19 18:14:44 Successfully updated ssm agent configuration



[Container] 2022/12/19 18:14:44 Registering with agent



[Container] 2022/12/19 18:14:44 Phases found in YAML: 1



[Container] 2022/12/19 18:14:44  BUILD: 7 commands



[Container] 2022/12/19 18:14:44 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED



[Container] 2022/12/19 18:14:44 Phase context status code:  Message: 



[Container] 2022/12/19 18:14:44 Entering execCommands



[Container] 2022/12/19 18:14:44 Entering phase INSTALL



[Container] 2022/12/19 18:14:44 Phase complete: INSTALL State: SUCCEEDED



[Container] 2022/12/19 18:14:44 Phase context status code:  Message: 



[Container] 2022/12/19 18:14:44 Entering phase PRE_BUILD



[Container] 2022/12/19 18:14:44 Phase complete: PRE_BUILD State: SUCCEEDED



[Container] 2022/12/19 18:14:44 Phase context status code:  Message: 



[Container] 2022/12/19 18:14:44 Entering phase BUILD



[Container] 2022/12/19 18:14:44 Running command pip install --upgrade pip



pyenv: version `3.8' is not installed (set by /codebuild/output/src981310543/src/.python-version)







[Container] 2022/12/19 18:14:45 Command did not exit successfully pip install --upgrade pip exit status 1



[Container] 2022/12/19 18:14:45 Phase complete: BUILD State: FAILED



[Container] 2022/12/19 18:14:45 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: pip install --upgrade pip. Reason: exit status 1



[Container] 2022/12/19 18:14:45 Entering phase POST_BUILD



[Container] 2022/12/19 18:14:45 Phase complete: POST_BUILD State: SUCCEEDED



[Container] 2022/12/19 18:14:45 Phase context status code:  Message: 

```

**Comment by dlpzx** [comment]
@zsaltys can you provide more details? I am not quite sure if I understand your issue. FYI: @noah-paige

**Comment by zsaltys** [comment]
@dlpzx when deploying data.all to aws all python based components fail due to this error:

"pyenv: version `3.8' is not installed (set by /codebuild/output/src981310543/src/.python-version)"

I had to set mycat .python-version to exactly 3.8.13 .. By default it was set to 3.8 because of https://awslabs.github.io/aws-dataall/deploy-aws/ which says: virtualenv venv -p python3.8

Basically if you want to reproduce this. Set .python-version to 3.8 and try to deploy data.all from scratch. It will fail with this error in CodePipeline: 

"pyenv: version `3.8' is not installed (set by /codebuild/output/src981310543/src/.python-version)"

**Comment by dlpzx** [comment]
I will update the docs. I have tested and I was able to deploy the infra without issue using python version 3.9
