### ISSUE TITLE
docker compose fails on macs for port 5000

### ISSUE THREAD

**Issue by zsaltys** [awslabs/aws-dataall#263]
### Describe the bug

docker-compose up fails with Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5000 -> 0.0.0.0:0: listen tcp 0.0.0.0:5000: bind: address already in use

due to:

https://medium.com/pythonistas/port-5000-already-in-use-macos-monterey-issue-d86b02edd36c

### How to Reproduce

run docker-compose up on a mac

### OS

Mac

### Python version

N/A

### AWS data.all version

N/A

**Comment by zsaltys** [comment]
workaround: https://developer.apple.com/forums/thread/682332

**Comment by dlpzx** [comment]
Yes, I ran into the same issue a while ago. I will close it as it is not a bug of data.all but a generic issue.

**Comment by zsaltys** [comment]
@dlpzx would it be worth using a different port than 5000 to avoid people rediscovering this issue?
