### ISSUE TITLE
Support other IDPs than Cognito

### ISSUE THREAD

**Issue by zsaltys** [awslabs/aws-dataall#264]
**Is your feature request related to a problem? Please describe.**
Our organization blocks access to AWS Cognito. We use OKTA.

**Describe the solution you'd like**
Make it possible to configure data.all to work with other IDPs.

**Comment by dlpzx** [comment]
@zsaltys Hello! There are several customers that are using data.all with other IdPs (including Okta). The chosen IdP does not replace Cognito, but it integrates with it, meaning that we use Cognito as a proxy.

Here there is a guide on how to integrate Cognito with Okta in data.all:
[data-all OktaCognito Integration.pdf](https://github.com/awslabs/aws-dataall/files/10286651/data-all.OktaCognito.Integration.pdf)

Please let us know if you need more help :)

**Comment by zsaltys** [comment]
@dlpzx thank you
