### ISSUE TITLE
S3 Bucket data sharing

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#284]
**Is your feature request related to a problem? Please describe.**
When I use tools in my ETL or data consumption applications, I often need direct access to the source data S3 Bucket. Lake Formation in some cases does not perform sufficiently fast and S3 access points do not integrate with some of the used tools. At the moment we solve this challenge by manually providing permission in the Bucket policy of the source Bucket.

**Describe the solution you'd like**
For this particular cases we would like an automated way to manage access to S3 Buckets. 
- We want a self-service workflow with sharing request and approval and at the same time 
- we want to use S3 Bucket policies under-the-hood.

**Describe alternatives you've considered**
We can re-use data.all sharing workflow and include a new type of sharing, S3 Bucket. To not over-complicate the resulting bucket policy we would not require a prefix-level grained access, granting access grants access to the whole S3 Bucket.

Changes needed:
(see comments below)

## Question
- **How should we manage imported Datasets?** When we import a Dataset, we are importing an existing S3 Bucket with its corresponding bucket policy which might be managed by other processes outside data.all. We need to define if data.all a) will ignore these buckets, b) can overwrite the bucket policy (I am not sure how) or c) if it will re-create it and manage it.
- **How do we define that a dataset is s3-bucket-shareable?** We need to clarify what is the user process to categorize a dataset as S3-bucket-shareable.
- Can a dataset be shared with LF-tables, Access points-folders and S3-Bucket mechanisms simultaneously? What are the limitations?
- How do we handle KMS keys for imported buckets? and in sharing how do we specify CMK keys?

## Design decisions and assumptions – We should write ADRs in the development fork
-	We will first implement the feature on data.all created datasets and then we will deal with imported datasets. 
-	Users can choose between 2 sharing models, granular-share and full-share. Dataset owners decide which model applies to their Dataset and shares will follow the chosen model. In the granular-share model, we share Tables (Glue tables) using Lake Formation and Folders (S3 prefixes) using S3 Access points, this is what is currently implemented. In the full-share model, the whole S3 Bucket is shared using Bucket policies and the whole Glue database is shared using Lake Formation. We will first implement the full S3 Bucket share and as optional the full database share.

**Comment by dlpzx** [comment]
I have created a branch to include the S3 Bucket policy changes (step 4 in the changes needed). However it is only for visibility, this branch should be rebased as V1.4.0 includes significant changes in the sharing workflow implementation.

**Comment by dlpzx** [comment]
In the feature branch I started drafting the solution. To avoid conflicts with other sharing mechanisms we assume that S3 Bucket sharing will only be used in certain datasets. The sharing mechanism will be decided at dataset creation and can be modified if there are no existing share objects:

![image](https://user-images.githubusercontent.com/71252798/223162479-c1ce0e49-6ce9-4505-81e5-5860ce124e09.png)

**Comment by dlpzx** [comment]
I created a new branch from V1.5 so that we start from the latest version and we do not need to rebase. The instructions listed above match the different commits in the branch. In most cases I just added TODOs wherever changes are needed.
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/71252798/234032242-2dfcab89-83ce-4fea-9302-e340297d7fcc.png">

**Comment by dlpzx** [comment]
Hi @zsaltys I had the same dilemma when designing the feature. We have 2 options, for full-share datasets we either a) index the S3 bucket instead of the tables and folders b) we index tables and folders as we do now and manage the pre-existing shares with messages and UI changes.

I went on with option b) because it adds more visibility on the content of the dataset. Users often search for a table that they know in the catalog in other words I did not want to decrease the discoverability of tables in the Catalog. But this is not set on stone and we are open to changes or new solutions

**Comment by zsaltys** [comment]
@dlpzx Thanks for your reply. I reviewed again the task but I don't think we currently explain what will happen in this scenario:

1) we create a bucket with s3 bucket policy sharing
2) we create 2 tables X and Y
3) a user from team A will request to share table X and get it approved
4) a different user from team A will see table Y in the catalog. They can request to share this table. However this is meaningless. The table would be already shared with them from step 3. This is confusing to the user.

My proposal would be that if we want to keep showing individual tables then we would need to show an indicator on the UI that the table is already shared with the environment and role that is requesting access.

**Comment by dlpzx** [comment]
## Update on Task G.3 - KMS keys handling and CMK keys - > when implementing imported Dataset

### Problem statement
At the moment KMS keys are not imported alongside the S3 Bucket when we import a Dataset. But when we share a dataset through S3 Bucket sharing, we will also need to grant permissions to the requester to the target dataset KMS key.
1) Give permissions (encrypt/decrypt) in the IAM policy of the requester to the KMS key id
2) Give permissions in the KMS policy to the requester IAM role

### Solution
Data.all release v1.6.0 is focused on security hardening and one of the task is hardening the IAM policies of all roles in data.all. As part of this task it has been necessary to add the KMS key as input when importing a dataset. See https://github.com/awslabs/aws-dataall/pull/515 

How does that affect us?
1) For giving permissions (encrypt/decrypt) in the IAM policy of the requester to the KMS key id we can use the same methods that we would use with a created dataset
2) Give permissions in the KMS policy - very similar to giving permissions in the S3 Bucket policy - we need to decide on how to manage pre-existing policies that are created outside of data.all. Should we append new policies? What are the permissions that the pivotRole needs?
