### ISSUE TITLE
Improve sharing notifications

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#291]
Currently sharing notifications inform me about the user that has approved a request and the target Dataset. I am missing information about the requester that got access and maybe the number of tables/folders shared.

Also there are only 2 types of notifications: approved or rejected. I would like to be informed about the success or failure of the sharing.

**Describe the solution you'd like**
I would like more types of notifications:
- approve: already implemented
- reject: already implemented
- revoke
- processed (maybe with failure/success information)

And in the notifications I would like to obtain information about:
- Dataset: already implemented
- Approver: already implemented
- Requester
- Number of tables/fodlers

**Comment by dlpzx** [comment]
Related to #166

**Comment by dlpzx** [comment]
Take a look at `dataall/cdkproxy/stacks/environment.py` , there is already a "subscriptions" construct that could be helpful
<img width="841" alt="image" src="https://github.com/awslabs/aws-dataall/assets/71252798/4d8c2a7f-c8d4-49cd-99a2-78981e3feb1d">

**Comment by dlpzx** [comment]
This issue can be close as it is done in #822 and #818

**Comment by anmolsgandhi** [comment]
Closing this issue in favor of #822 and #818
