### ISSUE TITLE
Unable to schedule reports from DataAll

### ISSUE THREAD

**Issue by MATTT-P** [awslabs/aws-dataall#308]
Although we can schedule reports in QuickSight to be distributed to emails, it is not possible do within DataAll

**Comment by dlpzx** [comment]
Hi @MATTT-P, I think I need more information to confirm your issue. 
In data.all we create Quicksight users of the `type=Quicksight`, some features of Quicksight are not enabled for this type of user. So we need to create users of `type=IAM`. This is explained in detail in #281
Please confirm that this is your issue and we can move the discussion to the other issue.

**Comment by dlpzx** [comment]
Hi @MATTT-P, this issue will be closed soon if no more information is provided. However it seems that the challenge is already addressed in #281

**Comment by dlpzx** [comment]
Closing stale issue. If needed it will be reopened
