### ISSUE TITLE
Navigation between DataAll Environments 

### ISSUE THREAD

**Issue by MATTT-P** [awslabs/aws-dataall#311]
Navigation between DataAll environments is difficult because it’s not possible to see which environment you are currently in from the URL, having the URL slug contain beta/test when in such environments would assist with this.

**Comment by dlpzx** [comment]
Hello again @MATTT-P,

I am guessing you are talking about the deployment environments =  data.all BETA, data.all TEST, data.all PROD right? Each of this is deployed in a different AWS account. I agree that AWS Cloudfront default distribution names  (random sequence of characters) do not contain much information. That is why we developed "custom domains" in data.all alongside other data.all customers. With this parameter you can set your own domain e.g.` https://dataallORGANIZATIONNAMEtest` . Check the deployment [documentation](https://awslabs.github.io/aws-dataall/deploy-aws/) for more details.
![image](https://user-images.githubusercontent.com/71252798/219322350-1c9d8103-52d6-4437-bfa5-67cfe419dcb3.png)

I also thought that you might be talking about data.all environments that are linked with the same deployment. Is this the case?

**Comment by dlpzx** [comment]
Closing stale issue. If needed it will be reopened
