### ISSUE TITLE
Unable to save favorites in order to get quick access in the future

### ISSUE THREAD

**Issue by MATTT-P** [awslabs/aws-dataall#312]
When using DataAll, it is not possible to save a favorite view or chart using the URL and saving it to your desktop etc.

This makes the navigating to the most used views very time consuming.
It also means you cannot create a specific drill down view to monitor a particular issue and save it.
Added to the complication of short timeout, makes navigating around DataAll unworkable at times.

**Comment by MATTT-P** [comment]
More information on this.

The ability to set filters and parameters on a dashboard and then save them, within the embedded dashboard in DA is not possible, we would like the functionality of saving the state brought into the embedded DA view.

**Comment by dlpzx** [comment]
You are talking about Quicksight right? I think the issue goes back to the type of user that data.all creates in Quicksight. It is explained in detail in #281

**Comment by dlpzx** [comment]
Closing stale issue. If needed it will be reopened
