### ISSUE TITLE
NACL in default VPC too broad

### ISSUE THREAD

**Issue by manjulaK** [awslabs/aws-dataall#319]
The default VPC allows too much access and in some cases can be problematic please reduce the NACL to allow required http/s and tcp ports required by the aplication

**Comment by dlpzx** [comment]
Hi @manjulaK, welcome to the repo! I believe this issue was already opened in #307 . Are you referring to the default VPC in used for the CICD resources?

**Comment by manjulaK** [comment]
hi @dlpzx I believe this issue is for both during installation and there after. The NACL on inbound rule to allow all traffic for all ports is also too broad post installation and hence need to be addressed as well. here is what has worked for me
<img width="1481" alt="Screen Shot 2023-02-22 at 6 13 45 AM" src="https://user-images.githubusercontent.com/241846/220619707-0d2b86a2-6dc5-4067-88c8-62097e9cf05d.png">
