### ISSUE TITLE
Add Default VPC Requirement for SageMaker Studio

### ISSUE THREAD

**Issue by noah-paige** [awslabs/aws-dataall#325]
**Is your idea related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
As of dataall's current state, Sagemaker Studio requires the default VPC to exist in the Environment. Can this be added to documentation/can we extend dataall's flexibility to provide custom VPCs for studio

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by dlpzx** [comment]
Solved in #409
