### ISSUE TITLE
Configurable method to determine if a linked account is CDK bootstrapped

### ISSUE THREAD

**Issue by jeffshep** [awslabs/aws-dataall#332]
**Is your idea related to a problem? Please describe.**
In an environment where accounts are CDK bootstrapped using the AWS Control Tower solution, the data.all opinionation to determine if an account has been CDK bootstrapped fails, as the expected Stack Name is hardcoded "CDKToolkit". 

**Describe the solution you'd like**
An additional stack name provided in the `cdk.json` that can also be looked-up in the backend logic.
Potentially supporting unique suffix identifiers in the stack name

**Comment by anmolsgandhi** [comment]
#719
