### ISSUE TITLE
Delete share request and check existing share request

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#35]
Whenever we create a share request, it cannot be deleted. The API for deletion of share_object does not exist. We need to create a new API that checks if a share object contains shared items and if it does not, then delete the item from the RDS shares table. To be able to use the API we also need to add a button in the frontend, for example next to "Submit"

![image](https://user-images.githubusercontent.com/71252798/174763721-280a250c-b33c-4d75-bd56-a477da1bcedd.png)

**Comment by LEUNGUU** [comment]
@dlpzx Hello. May I know more detail about this issue?  I want to take this. Thanks!

**Comment by LEUNGUU** [comment]
@dlpzx Thanks for your comments. In a word, the goal of this feat. is to add a "delete" functionality of share object which allows user to delete share request which does not have shared items. But if the share request has shared items, user need to delete shared items first. Am I right?
