### ISSUE TITLE
SageMaker Studio Kernel fails to start

### ISSUE THREAD

**Issue by atzev** [awslabs/aws-dataall#351]
### Describe the bug

data.all users who use SageMaker Studio cannot launch Studio Notebooks due to connectivity issues. The Kernel fails to stsart

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
- A user creates a profile in data.all and logs in to SageMaker Studio. 
- The user goes to File->New->Create to create a new notebook and selects the image and instance type
- SageMaker studio takes few minutes trying to start the Kernel. At the end it gives an error message "Failed to launch app []SageMaker studio is unable to reach SageMaker Endpoint. Please ensure your VPC has connectivity to SageMaker via Internet or VPC Endpoint"

### Expected behavior

The Kernel starts and the user can start writing code in the notebook

### Screenshots

<img width="1407" alt="Screenshot 2023-03-05 at 23 24 33" src="https://user-images.githubusercontent.com/87728145/223115089-e575addf-cdb3-4432-baf5-e43e8d01db82.png">

### OS

Mac

### Python version

3.8

### AWS data.all version

1.4.1

**Comment by dlpzx** [comment]
This is solved and explained in #409
