### ISSUE TITLE
Scope down tagging permissions for pivot role

### ISSUE THREAD

**Issue by nguforw** [awslabs/aws-dataall#370]
**Is your feature request related to a problem? Please describe.**
The PivotRole currently defines a permissions policy that permits all `tag:*` and `resource-group:*` actions on all resources. As I use automation to deploy this into multiple accounts, this policy results in a cfn-nag failure in my deployment pipeline.

**Describe the solution you'd like**
I'd like the tagging permissions to be scoped down to specific actions and as a stretch goal, scoped down to resources that can be matched to a pattern used by data.all.

**Describe alternatives you've considered**
I am currently applying a cfn-nag suppression to get this to validate in my pipeline and I would rather not do so.

**Additional context**
N/A

**Comment by dlpzx** [comment]
Hi @nguforw, thanks for opening the issue! The pivotRole is definitely something to keep on improving, we will consider this feature in our planning discussions.

**Comment by dlpzx** [comment]
This issue will be addressed in #491
