### ISSUE TITLE
Replace dataset glue-handler custom resource by CDK constructs

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#381]
When a dataset is deployed we use a custom resource to create a Glue Database and grant permissions to the database. Now several constructs of CDK enable us to replace the custom resource. 
https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_lakeformation/CfnPermissions.html 

**Describe the solution you'd like**
Easier management of dataset resources avoiding custom resources.

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by anmolsgandhi** [comment]
Our customized custom resource cannot be directly replaced by CDK construct
