### ISSUE TITLE
Error when copying role for Data Team from the teams tab

### ISSUE THREAD

**Issue by manjulaK** [awslabs/aws-dataall#389]
### Describe the bug

1) Data team is not able to copy the credentials for assuming role from the Env->Teams tab
2) As an Env Admin when we copy the credentials for data team it is incorrect and this makes it impossible for the consumption team to run aws commands. and hence this is a critical functional issue. 

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

1) Data team is able to copy the credentials for assuming role from the Env->Teams tab
2) Or  Env Admin can copy correct credentials for data team for the data team

### OS

all

### Python version

3.1

### AWS data.all version

1.4.2

**Comment by dlpzx** [comment]
@manjulaK thanks for raising the issue! It is solved in the linked PR :)
