### ISSUE TITLE
Very high costs related to kms key encryption

### ISSUE THREAD

**Issue by TimBYara** [awslabs/aws-dataall#393]
My setup:
Basically, I created a dataset and a pipeline in data.all. The pipeline is currently scheduled every 5 minutes. During the pipeline execution, I fetch some data points from an API, I transform the data and finally add the transformed data to the dataset. In addition, I created a quick sight dashboard that shows the data added to the dataset in some plots.

Some details:
The pipeline consists of 3 separate lambda functions. One for fetching the data, one for transforming the data and one for storing the data. To store data I am using awswrangler:
```
        results = wr.s3.to_parquet(
            df=df,
            path=os.path.join(dataset_s3_bucket, glue_table),
            dataset=True,
            mode='append',
            database=glue_database,
            table=glue_table,
            boto3_session=env_session,
            dtype=dtypes,
            description=description,
            columns_comments=comments
        )
```
This will create a new parquet file in the S3 bucket connected to the data.all dataset. 

The problem:
I realised that the costs for kms keys in our account are increasing everyday and it starts to be expensive. In CloudTrail, I found that there are an enormous amount of kms decryption operations executed. I looks like when quick sight is loading new data, every file that was added to the dataset (glue table) will be decrypted individually. Since the number of files is increasing quickly, the costs also go up. 

Question:
Is this the intended behaviour? How can/should I setup the workflow to make the costs independent of the number of files? Could something be done to fix this on the platform level or is data.all simply not the correct tool for problems with a lot of small files?

**Comment by dlpzx** [comment]
Hi @TimBYara, thanks for opening an issue. It is great to see customer usage of data.all :) Unfortunately I think your issue might be on the Quicksight side. Let me go through the docs and reach out internally to some specialists to see what we can do to remediate the situation.

**Comment by TimBYara** [comment]
> Hi @TimBYara, thanks for opening an issue. It is great to see customer usage of data.all :) Unfortunately I think your issue might be on the Quicksight side. Let me go through the docs and reach out internally to some specialists to see what we can do to remediate the situation.

Thank you for looking into this.

**Comment by dlpzx** [comment]
It will be re-opened if needed.
