### ISSUE TITLE
Not All Shared DBs Showing in Worksheet View

### ISSUE THREAD

**Issue by noah-paige** [awslabs/aws-dataall#401]
### Describe the bug

If you have 2 shares from 1 dataset table to an environment - 1 for Environment Team IAM Role and 1 for Consumption Role:

When trying to query a shared Database using Data All Worksheets only 1 Shared Database appears in the drop down for Worksheet Databases. This shared database name could be the one shared with the consumption role and NOT the one shared to the user team. 

User will then receive `Insufficient Lake Formation` permissions when trying to query using Worksheets since it is the incorrect database name with respect to the shared database name for the user team (not the consumption role)

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

All shared database names to the consumer environment should be listed in the Worksheets View Database drop down 

### OS

N/A

### Python version

N/A

### AWS data.all version

v1.4.3

**Comment by dlpzx** [comment]
Resolved
