### ISSUE TITLE
Glue Crawler configuration

### ISSUE THREAD

**Issue by chamiles** [awslabs/aws-dataall#407]
Ability to configure glue crawler or a "click to" to the console to allow editing of crawler classification and crawler settings.

currently required to go find glue crawler in console and make updates before being able to crawl files that need specific classification, this would be useful for Line of business users that are just uploading a onetime csv dataset and are not familiar with AWS console.

**Comment by dlpzx** [comment]
Nice feature! Thanks for adding it @chamiles

**Comment by anmolsgandhi** [comment]
We evaluated this issue, The requirements for this issue seems to be equivalent to recreating glue console in data.all and is not highly requested as of now. Feel free to reopen this if its still a requirement.
