### ISSUE TITLE
Option to disable data preview

### ISSUE THREAD

**Issue by thuerst** [awslabs/aws-dataall#41]
Catalog and Datasets discovery features offer a data preview for datasets. This preview is accessible before a user has been granted read access to a dataset. Users with only logon permissions to Data.All are able to browse & preview all datasets. This includes datasets which may contain sensitive information.

It should be possible to disable the data preview for selected datasets. This could be handled though a flag set during dataset creation/edit or by using the existing "Confidentiality" setting.

**Comment by dlpzx** [comment]
Hi thuerst,
Your proposal of using the confidentiality metadata as flag to enable or disable preview is already implemented :) 
When a dataset is classified as secret or official, for users that are not data owners of the dataset a message like the following appears:

![image](https://user-images.githubusercontent.com/71252798/173305772-01478a94-5192-4eb1-a10e-246324da5a2f.png)

This level pf permissions is defined in the `preview` resolver in `backend/dataall/api/Objects/DatasetTable/resolvers.py` , in case you want to implement further permissions
