### ISSUE TITLE
ECS containers should be limited to read-only access to root filesystems

### ISSUE THREAD

**Issue by tvancasteren** [awslabs/aws-dataall#426]
### Describe the bug

The ECS containers deployed by data.all in the Deployment account have both read- and write access to the mounted root filesystem. This generates security alerts in AWS Security Hub and AWS Trusted Advisor.

This involves all 7 Task Definitions deployed by data.all in the Deployment account:
- dataall-dev-catalog-indexer
- dataall-dev-cdkproxy
- dataall-dev-policies-updater
- dataall-dev-share-manager
- dataall-dev-stacks-updater
- dataall-dev-subscriptions
- dataall-dev-tables-syncer

Remediation guidance for this issue has been described here: https://docs.aws.amazon.com/securityhub/latest/userguide/ecs-controls.html#ecs-5 

![image](https://user-images.githubusercontent.com/105369345/233353869-54a4aa44-e5d5-427c-ae36-ae0ad79852f6.png)

### How to Reproduce

A default deployment of data.all will result in these alerts.

### Expected behavior

Apply read-only access to the root file system on all 7 ECS Task Definitions.
The ReadonlyRootFilesystem parameter in the container definition of the ECS Task Definitions should be set to true.

### OS

N/A

### Python version

N/A

### AWS data.all version

v1.4.3

**Comment by dlpzx** [comment]
Agree, let's work together on fixing this issue

**Comment by noah-paige** [comment]
Closing issue - implemented in v1.6
