### ISSUE TITLE
Deployment issue - The S3 bucket that you specified for CloudFront logs does not enable ACL access

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#433]
### Describe the bug

As explained in the [docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html), If your bucket uses the bucket owner enforced setting for S3 Object Ownership, you must use policies to grant access to your bucket and the objects in it. Requests to set ACLs or update ACLs fail and return the AccessControlListNotSupported error code. Requests to read ACLs are still supported. Also explained [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html). 

Some organizations enforce disabling ACLs in their S3 Buckets, which results in failures in the CloudFront deployment stage.

![image](https://user-images.githubusercontent.com/71252798/234573390-0eb4e2bb-7438-40c5-b595-e6abd8055150.png)

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
Deploy or update data.all in an AWS accounts that disables ACLs in S3 Buckets

### OS

n/a

### Python version

n/a

### AWS data.all version

v1.5.0

**Comment by akaitoua** [comment]
Hello Adriana, 
I have solved this issue. I can merge the solution if no one picked this one yet.

**Comment by nikpodsh** [comment]
Hello @akaitoua,

Thank you very much for your help!
No one has taken this issue yet. Let me take a look at your PR :)

**Comment by akaitoua** [comment]
@nikpodsh, would you merge the pull request? I do not have write permissions to merge the pull request.
