### ISSUE TITLE
Error while deploying locally on MacBook Pro M1 

### ISSUE THREAD

**Issue by pruthvirajksuresh** [awslabs/aws-dataall#45]
Hello team ,

I am getting the below error while deploying the data all on macbookpro m1 

container Name :-  "aws-dataall_cdkproxy)"

Error Message:-
"qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory"'

Any solution would be helpful. 

Thank you , 
Raj

**Comment by louishourcade** [comment]
Hello,
Thanks for raising this issue. I personally don't work with a Mac M1 but I know some colleagues that do, and managed to solve the issue with data.all local deployment. I'm forwarding them the question internally to see if they can help you.
Best

**Comment by pruthvirajksuresh** [comment]
Thank you @louishourcade
