### ISSUE TITLE
Deleting consumption roles before deleting shares causes issuews

### ISSUE THREAD

**Issue by manjulaK** [awslabs/aws-dataall#451]
### Describe the bug

When a consumption role is deleted there are no warnings to delete the shares but later the Share UI stops working and there are several errors for the entire team. This needs to be fixed.

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

Deleting consumption role with orphan shares should not be allowed.

### OS

All

### Python version

3.1

### AWS data.all version

v1.3,v1.4,v1.5

**Comment by dlpzx** [comment]
same as #450
