### ISSUE TITLE
Limit PivotRole trust relationships [Permissions Clean up]

### ISSUE THREAD

**Issue by manjulaK** [awslabs/aws-dataall#474]
### Describe the bug

Pivot Role Trust Relationships:

Can you kindly consider locking down only the required services to be able to assume the data.all pivot role from the central to the linked accounts.  This would greatly help in ensuring Principles of Least Privilege are met.

From the cloud trail logs I see only the following roles from central **assuming this role:****

1. arn:aws:sts::***********:assumed-role/dataall-sandbox-graphql-role/
2. arn:aws:sts::***********:assumed-role/dataall-sandbox-awsworker-role/
3. arn:aws:sts::***********:assumed-role/dataall-sandbox-ecs-tasks-role/

We can start with and test further?

**Comment by dlpzx** [comment]
Thanks @manjulaK, we will fix it for v1.6

**Comment by dlpzx** [comment]
This item is duplicated #491
