### ISSUE TITLE
Creation of Dataset fails

### ISSUE THREAD

**Issue by marjet26** [awslabs/aws-dataall#475]
### Describe the bug

The Node.js Version needs to be updated. CloudFormation logs 

`resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 60891d40-7199-4e22-a3ca-21ba40f2ef36)" (RequestToken: e89d2d8c-8cc9-e15d-1fa0-91623b8e4abc, HandlerErrorCode: InvalidRequest)`

### How to Reproduce

```
Create a dataset from Data.all console
```

### Expected behavior

Dataset is correctly created. 

### Screenshots

![Screenshot 2023-05-24 at 09 23 45](https://github.com/awslabs/aws-dataall/assets/117375130/f118869f-7989-4746-afa0-f1dfb5ff1be7)

### OS

linux

### Python version

3.7+

### AWS data.all version

1.5.0

**Comment by dlpzx** [comment]
Thanks @marjet26 I was able to reproduce the issue. We are working on a fix as this is a priority issue

**Comment by dlpzx** [comment]
It is related to this issue: https://github.com/awslabs/aws-dataall/issues/425
