### ISSUE TITLE
Limit PivotRole permissions for Glue [Permissions Clean Up]

### ISSUE THREAD

**Issue by mourya-33** [awslabs/aws-dataall#477]
### Describe the bug

Pivot Role permissions for policy-0

Can you kindly consider locking down the glue service actions to only the required resources. This would greatly help in ensuring Principles of Least Privilege are met.

The glue service actions are currently set to access all resources (*). Please split this policy to restrict permissions for Glue Job and Crawler actions to only allow permissions on resources that have a **resourceprefix** (set during deployment). 
Glue actions for managing the catalog can be set to access all resources.

### How to Reproduce

N/A

### Expected behavior

The permissions need to be split into different sets - one for the glue job and crawler actions limiting the permissions to resources with resourceprefix only and the other for manage catalog actions to all resources.

### OS

Mac

### Python version

3.10

### AWS data.all version

1.5

**Comment by dlpzx** [comment]
Closing as it is duplicated
