### ISSUE TITLE
The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions

### ISSUE THREAD

**Issue by drankard** [awslabs/aws-dataall#479]
### Describe the bug

The CloudFront stack is making us of a very old version of the cloudfront-authorization-at-edge Serverless Application (2.0.4)
It so old that no tag exists in github, the oldest release version i 2.0.16 and is from Oct 21. 
It may not have been a deployment problem until now, when lambda node runtime 12.x is deprecated. 

Deployment fails with message: 
Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions.

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

https://github.com/awslabs/aws-dataall/blob/b44125801d76e53557df4400c5d63600eedb4e9d/deploy/stacks/auth_at_edge.py#L26

### How to Reproduce

```
Deploy CloudFront stack
```

### OS

Linux

### Python version

CodePipeline default

### AWS data.all version

main

**Comment by dlpzx** [comment]
Thanks for raising the issue @drankard, you are absolutely right, I was able to confirm the node version of the CloudFront Lambdas:
![image](https://github.com/awslabs/aws-dataall/assets/71252798/691c9c64-5d09-4144-94fc-f2fbf0784f19)

For some reason, it allowed me to deploy 5hours ago. We will look into it right away

**Comment by dlpzx** [comment]
@drankard, I am performing some testing with the latest semantic version of the application ([here](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/master/example-serverless-app-reuse/reuse-complete.yaml)). Once the testing on the following is complete I will open a PR.

- [ ] pre-existing deployments
- [ ] new deployments

**Comment by dlpzx** [comment]
This issue has been fixed in #480
