### ISSUE TITLE
SageMaker domain

### ISSUE THREAD

**Issue by dosiennik** [awslabs/aws-dataall#48]
Got a question about SageMaker domain, as far as I have noticed it needs to be setup manually as a prerequisite. Is there any reason for it or any plans to make it automatic?

**Comment by JahedZ** [comment]
Hi, although I don't have a release date to communicate yet, we do have CDK code to automatically provision a Sagemaker Domain upon creation of a data.all environment. In the meantime, you do have to setup the domain manually to leverage Sagemaker Studio features. (cc @dlpzx)

**Comment by dosiennik** [comment]
@dlpzx thanks for adding it to the roadmap. 

Do you have any release date in mind? Asking since this feature got quite important to us and currently we consider implementing it by ourselves vs waiting for it to be released - although here we are not sure how much effort it requires and when you are planning to release it.

Apart from that  in case we will need to implement it by ourselves we need to know if there are any specific requirements for the domain - like tag values etc.

@JahedZ has mentioned that you have already had some code for it.

**Comment by JahedZ** [comment]
@louishourcade I was hoping to submit the Pull request next week. This includes Automatic creation of a Sagemaker domain upon creation of a data.all environment, using minimal settings with direct internet access (Depending on customers, they would need to customize their settings).

Once this is done, I would also like to modify the creation of Sagemaker user profiles. Following [this blog post](https://aws.amazon.com/fr/blogs/machine-learning/enable-amazon-sagemaker-jumpstart-for-custom-iam-execution-roles/), we can make it so data.all users can access Sagemaker Jumpstarts and Sagemaker Projects

**Comment by louishourcade** [comment]
Alright thanks @JahedZ for the clarification. If you want, I have the code of a previous version of data.all in which we were creating SageMaker domains as part of the environment stack. If that could help, tell me and I'll send it to you.

**Comment by dosiennik** [comment]
@JahedZ hope you are fine :) sorry for disturbing you. Can I ask you about the plans/estimated date for creating a PR for this? Thanks in advance.

**Comment by JahedZ** [comment]
Hi @dosiennik, my apologies for the delay.
I opened this PR https://github.com/awslabs/aws-dataall/pull/82
Hope this helps :)
