### ISSUE TITLE
Minimize the permissions of Environment Team Role

### ISSUE THREAD

**Issue by mourya-33** [awslabs/aws-dataall#494]
### Describe the bug

Attached is the review of enhancements (please check column status) and anything with NeedsFixing is top priority and has to be addressed . CleanupEnhancements are very important as access to unused resources is not good to have .
followed by Good Enhancement. Please let me know if questions. The items marked review are candidates that can be explored for further clean up. What would be good is if you can add version on which issue will be fixed against each item and that will give us clear idea of what to expect.

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

Permissions for the team role must be minimally permissive.

### Screenshots

[IAMRolesandPermissionAnalysis-EnvTeamRole.xlsx](https://github.com/awslabs/aws-dataall/files/11630161/IAMRolesandPermissionAnalysis-EnvTeamRole.xlsx)

### OS

All

### Python version

3.10

### AWS data.all version

v1.3,v1.4,v1.5

### Additional context

Having least privilege is always good. and we request you to minimize the permissions for pivot role so that it follows the principles of least privilege.

**Comment by dlpzx** [comment]
This item is duplicated: #462
