### ISSUE TITLE
No such directory/env : bash

### ISSUE THREAD

**Issue by vinay650** [awslabs/aws-dataall#502]
### Describe the bug

When I try to deploy locally, and do docker compose up, all containers start running except graphql, it keep restarting again and again, and in logs keep printing no such directory/env : bash, and 
In the ui it's showing network error 
Can you quickly help me out

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
docker- compose up

### Expected behavior

Need  to perfectly run data.all

### OS

Win

### Python version

3.8

### AWS data.all version

Current

**Comment by dbalintx** [comment]
hello @vinay650 , could you provide further details which would help with the reproduction of your issue? For example logs, screenshots etc. 
Could you describe to process that you are following when you are trying to deploy locally?

**Comment by vinay650** [comment]
Hy I just followed deploy locally steps
1) git clone 
2) cd aws-datall
3) docker-compose up

After this 5 containers starts running, all seems to run fine except one named aws-graphql, in logs it's printing no such file or directory/ env:bash

**Comment by vinay650** [comment]
I just followed same steps and when I run the local host ui it's shows the UI but gives a prompt error for network not found

**Comment by dbalintx** [comment]
Hi @vinay650 ,

Thank you for the explanation.
Could you please provide the version of docker and docker-compose? by executing:
docker --version
docker-compose --version

Also, could you paste here the log that contains the error? 
(Please keep in mind to remove/mock any sensitive information eg. account id from the logs before providing it).

**Comment by vinay650** [comment]
docker --version is Docker version 20.10.12, build e91ed57
docker-compose version 1.29.2, build 5becea4c (  THIS IS LATEST )

logs --
: No such file or directory

: No such file or directory

: No such file or directory

: No such file or directory

: No such file or directory

: No such file or directory

: No such file or directory

: No such file or directory

: No such file or directory

: No such file or directory

: No such file or directory

Can u please help asap. Thank u !

**Comment by anmolsgandhi** [comment]
Closing this in favor of another recent issue, follow the thread on #765. Feel free to reopen if you have any questions!
