### ISSUE TITLE
Profiling Job failing with error: ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips 26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#506]
### Describe the bug

When running a profiling job in a table, we get the following error:
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips 26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### OS

n/a

### Python version

3.8

### AWS data.all version

1.5.4

**Comment by noah-paige** [comment]
Closing this issue as above error fixed in v1.6 - to track additional bug fixes necessary in #533
