### ISSUE TITLE
Limit KMS keys policies

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#512]
**Is your idea related to a problem? Please describe.**
As an additional layer of security besides restrictive IAM policies, I would like more specific KMS policies that restrict access to the KMS keys to the minimum.

**Describe the solution you'd like**
Define a KMS policy in CDK that restricts access to the different KMS keys to the IAM roles that use them in each case. Here is a list of keys that need an additional policy:
-TBD
-TBD

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by noah-paige** [comment]
Leaving open until v1m6m0 release and merge to main

**Comment by noah-paige** [comment]
Implemented in v1.6
