### ISSUE TITLE
Multi account/environment provisioning issue

### ISSUE THREAD

**Issue by mbdesai1989** [awslabs/aws-dataall#527]
### Describe the bug

Hi Team,

While we are trying to provision multiple environments using `cdk.json` we are getting below error in the CodePipeline step `dataall-dev-cloudfront-stage`, the below is the error from CloudFormation stack:

```
Embedded stack arn:aws:cloudformation:us-east-1:xxxx:stack/dataall-dev-cloudfront-stage-cloudfront-sta-AuthAtEdgeNestedStackAuthAtEdgeNestedStack-QNP7ORNK25TK/xxxxxx was not successfully created: The following resource(s) failed to create: [dataalldevauthatedge].
```

Thanks,
Mitesh Desai

### How to Reproduce

we are getting below error in the CodePipeline step `dataall-dev-cloudfront-stage`, the below is the error from CloudFormation stack:

```
Embedded stack arn:aws:cloudformation:us-east-1:xxxx:stack/dataall-dev-cloudfront-stage-cloudfront-sta-AuthAtEdgeNestedStackAuthAtEdgeNestedStack-QNP7ORNK25TK/xxxxxx was not successfully created: The following resource(s) failed to create: [dataalldevauthatedge].
```

### Expected behavior

Pipeline successful

### OS

Mac

### Python version

3.8.9

### AWS data.all version

1.5.0

**Comment by jeffshep** [comment]
Upgrade to version >1.5.3, there was a fix to update the NodeJS runtime for the Lambda@Edge functions. See the release here: https://github.com/awslabs/aws-dataall/releases/tag/v1.5.3

**Comment by dlpzx** [comment]
Hi @mbdesai1989, thanks for opening the issue. I agree with @jeffshep on the node runtime version issue hypothesis. In any case you can attach the specific CloudFormation logs here to see what the issue is exactly about

**Comment by mbdesai1989** [comment]
@dlpzx the error shared above is the error picked up from CloudFormation logs from the cloudfront stack on the first environment

**Comment by dlpzx** [comment]
@mbdesai1989, yes, I mean the error in particular for the failed resource. Maybe I am wrong and this is all you got, but I think in CloudFormation, in the nested stack you will get a log on the resource that failed (`dataalldevauthatedge` and why

**Comment by mbdesai1989** [comment]
I upgraded the code to 1.5.4 as suggested and it works fine now!
