### ISSUE TITLE
Environment description not saved

### ISSUE THREAD

**Issue by martonjuhaszyara** [awslabs/aws-dataall#54]
### Describe the bug

When linking a new environment in Data.all, the description given in the "Short description" field won't be saved after linking

### How to Reproduce

1. Go to Organizations and select one
2. Go under Environments tab
3. Click 'Link Environment'
4. Fill out form with description field and click on 'Create Environment' button
5. Check out the newly created environment, the description should be empty

### Expected behavior

Step 5. The description on the create environment form should persist after linking environment

### OS

Mac

### Python version

NA

### AWS data.all version

NA

**Comment by LEUNGUU** [comment]
Root cause is founded. PR will be raised.
