### ISSUE TITLE
OpenSearch stack failed during backend deploy due to length of policy name

### ISSUE THREAD

**Issue by rbernotas** [awslabs/aws-dataall#540]
### Describe the bug

Our "envname" as described in cdk.json is "staging".  Using this envname, the dataall CICD backend stage CF stack is failing because of error in the OpenSearchCollectionEncryptionPolicy:

Properties validation failed for resource OpenSearchCollectionEncryptionPolicystaging with message: #Name: expected maxLength: 32, actual: 33 #Name: failed validation constraint for keyword [pattern]

The name of the policy is too long due to the envname "staging".

In the file aws-dataall/deploy/stacks/opensearch_serverless.py (L49-58):

`        cfn_encryption_policy = opensearchserverless.CfnSecurityPolicy(
            self,
            f'OpenSearchCollectionEncryptionPolicy{envname}',
            name=f'{resource_prefix}-{envname}-encryption-policy',
            type='encryption',
            policy=self._get_encryption_policy(
                collection_name=self.cfn_collection.name,
                kms_key_arn=key.key_arn,
            ),
        )`

The name here would be dataall-staging-encryption-policy (33 chars) when the limit must be 32 chars.

In the meantime a workaround fix would likely be to change the name to {resource_prefix}-{envname}-encrypt-policy.

In the long term there should be a fix to have a truncate mechanism to prevent the error in the Policy name length, or warn the user about the length of their envname in the cdk.json.

### How to Reproduce

Run a deploy with the envname in cdk.json of "staging".  OpenSearch deploy in the backend stack deploy will fail on the length of Policy names due to the length of the envname.

### OS

N/A

### Python version

N/A

### AWS data.all version

1.5

**Comment by dlpzx** [comment]
Merged and released with v2.1.0 🚀
