### ISSUE TITLE
User unable to submit a new share request when an earlier requested dataset was deleted

### ISSUE THREAD

**Issue by anushka-singh** [awslabs/aws-dataall#544]
### Describe the bug

If user requested access for a dataset, and the dataset is then deleted by producer while sharing is in progress, the user is unable to submit a new share request for any other dataset as well. The user will keep seeing an error like this: ``An error occured (ResourceNotFound): Resource Dataset with URI xxxxx was not found``

### How to Reproduce

1. User 2 requested access to dataset 1 and submitted the request.
2. User 1 the creator of dataset1 then deleted dataset1.
3. User2 logged into data.all to request access to dataset2, and is able to create the request, but not submit it. The shares 4. 4. Page in SENT tab is stuck showing error: `An error occured (ResourceNotFound): Resource Dataset with URI xxxxx was not found` , thus preventing user2 from submitting any other requests as well.

### Expected behavior

User should be able to submit another request without any problems and an older dataset deletion should not impact the user. 

### OS

Mac

### Python version

3.9

### AWS data.all version

1.5

**Comment by noah-paige** [comment]
I was able to replicate the above behavior in my local deployment of data.all

It appears the `ShareObject.existingSharedItems` field is not resolving to the correct value when checking if the Dataset Object has existing shared items before deleting.
