### ISSUE TITLE
Consumption Role does not behave as expected

### ISSUE THREAD

**Issue by marjet26** [awslabs/aws-dataall#555]
### Describe the bug

According to the documentation, consumption role should grant access an IAM Role to a dataset. However, when viewing LakeFormation permissions, the permissions is being granted to an AWS Account.

### How to Reproduce

```
1. Create an IAM role in the AWS account of the requestor account.
2. Register the IAM role as a consumption role. 
3. Create a share request using the consumption role. 
4. Approve the share request.
5. View permissions of the Table in LakeFormation. 

```

### OS

linux

### Python version

3.7+

### AWS data.all version

1.5.4

**Comment by dlpzx** [comment]
Hello @marjet26, I am going to need some more information :) 
As it is explained in this [blogpost](https://aws.amazon.com/blogs/big-data/securely-share-your-data-across-aws-accounts-using-aws-lake-formation/) when we share:
1. from source: we share the table and database with the target account = open RAM invitation
2. from target: we accept the RAM invitation
3. from target: we create a resource link table
4. from target: we grant permissions to the resource link table to the requester role

What account are you checking the LF permissions source or target?

**Comment by marjet26** [comment]
The correct LakeFormation Principal (ConsumptionRole) was assigned permissions.
