### ISSUE TITLE
jsonschema == 3.2.0 failing Glue jobs SyntaxError: invalid syntax (py310compat.py, line 5)

### ISSUE THREAD

**Issue by sheetalchauhan24** [awslabs/aws-dataall#559]
### Describe the bug

The glue jobs that are getting build in Data.all Pipeline are getting failed due to issues in jsonschema(3.2.0) package.
There was a latest release in the package on 6th July 2023 and I suspect that lead to this situation. By downgrading the package to jsonschema==3.0.2 glue jobs worked fine. 

### How to Reproduce

Create a new data.all my data pipeline add a glue job and execute glue job

### OS

Linux

### Python version

3.7

### AWS data.all version

v1.0

**Comment by dlpzx** [comment]
Hi @sheetalchauhan24, the pipeline blueprint with Glue Jobs was deprecated a few versions ago. We are not working on it at the moment. However we are exploring ways of integrating it back once v2.0.0 is released. In v2.0 we are refactoring the code to allow features to be customizable (e.g. pipelines using DDK or blueprints). We will take your finding and include it if we resurrect the blueprints in v2.X

**Comment by anmolsgandhi** [comment]
Since there has been no further communication, we are closing this issue. Please feel free to reopen the issue if you have any more questions or require further assistance.
