### ISSUE TITLE
CodeBuild fails on prod branch - version / dependency issues?

### ISSUE THREAD

**Issue by gavclark** [awslabs/aws-dataall#611]
### Describe the bug

CodeBuild is failing at the unit test stage in PROD branch (this started happening on 28/07/2023, previous pipeline builds completed successfully previously) :

![image](https://github.com/awslabs/aws-dataall/assets/16735754/b84d4356-26bd-4b04-b147-a6d4543ba6d6)

In the build log - the following is listed as the error/failure:
![image](https://github.com/awslabs/aws-dataall/assets/16735754/f7a03297-e7e0-4482-b331-fb6817c1b12f)

Further up in the log, this looks to be associated:
![image](https://github.com/awslabs/aws-dataall/assets/16735754/b389cc91-374b-42d5-a30e-c6bace54c7be)

I am not sure if this is related to version dependencies etc. There are items in the log which may suggest this:
![image](https://github.com/awslabs/aws-dataall/assets/16735754/b109f8bd-dc5e-4152-ba5a-8aa3b659ba4f)

We have recently merged 1.5x into the DEV branch of the dataall repository as part of our upgrade plans. As these are two different branches (DEV vs. PROD) I don't think they are related , but thought I'd mention it.

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
Make a code change to a pipeline and push the changes to trigger a build

### Expected behavior

Pipeline build completes successfully

### OS

n/a

### Python version

3.7

### AWS data.all version

0.9

**Comment by dlpzx** [comment]
Hi @gavclark, your pipeline looks slightly different from the open-source pipeline. In the open-source version there is a quality gate where we run a CodeBuild stage called "IntegrationTests". I would need to have a look at how you are defining your tests. Are you aware of any customization?

**Comment by gavclark** [comment]
Hi @dlpzx , I am not sure what customisation has been done (by 3rd party) - what information would you need to see how we have defined our tests ? something from the CodeBuild project / configuration ?

**Comment by dlpzx** [comment]
Hi @gavclark, we can have a look at the tests directly. I can see that your tests are located in a folder called `tests/unittests`. In data.all this folder does not exist, either you created your own tests or you used the tests in data.all `test` folder as basis. Maybe we can schedule a call to look at the code itself and sort it out

**Comment by anmolsgandhi** [comment]
Confirmed with @dlpzx that the issue has been resolved offline which involved custom code. Please feel free to reopen the issue if you still have questions!
