### ISSUE TITLE
Error when creating ML Studio

### ISSUE THREAD

**Issue by joel-farvault** [awslabs/aws-dataall#62]
### Describe the bug

The Sagemaker ML Studio domain has been created and once I launch a ML Studio from Data.all, I get the following error message: Expected Iterable, but did not find one for field 'SagemakerStudioUserProfile.sagemakerStudioUserProfileApps'.

![image](https://user-images.githubusercontent.com/61437090/175829272-7077cbf8-dbf7-4174-a806-4abe5f57660d.png)

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

I would expect to open ML Studio

### OS

Mac

### Python version

3.7

### AWS data.all version

v1.0.0

**Comment by dosiennik** [comment]
I think it has been fixed: https://github.com/awslabs/aws-dataall/issues/47 ?
