### ISSUE TITLE
CDK execution role (custom template) throws S3 access denied error for pivotRole auto-created nested stack

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#625]
### Describe the bug

When using the `cdk bootstrap` with the new IAM policy provided in the UI some policies seem to be missing to access the template for the nested template in S3.

We created the IAM policy and bootstraped, then when linking the environment, the CloudFormation stack failed with a CREATE FAILED - S3 access denied from the nested pivotRole stack.

The nested stack does not even get created +  there are no S3 calls in the pivotRole stack. Both suggest that the issue is on reading the CloudFormation template from the S3 bucket that CDK uses to store the synthesized template.

We tested using the Administrator policy in the bootstrap command and trying to link again and it works without issue. We can confirm that the issue is in the CDK custom exec role and that is missing some S3 policies

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### OS

na

### Python version

na

### AWS data.all version

V1.6.1

**Comment by dbalintx** [comment]
I'd also polish the frontend a bit under this issue to make clear the differentiation between the 2 kind of bootstrapping method.
