### ISSUE TITLE
SqlPipeline to DataPipleine migration is not completing as expected at dataall-dev-dbmigration-stage stage

### ISSUE THREAD

**Issue by MATTT-P** [awslabs/aws-dataall#637]
### Describe the bug

When running through the build process, the sqlpipeline to datapipleine migration, is not completing as expected at the dataall-dev-dbmigration-stage stage.

There two new column added to data pipeline which are devstages and devstrategy which cannot be null, but during creation no default values are set.

1. In the first script, db migration script is creating two new columns devStrategy and devStage which can be null.  
 
![image](https://github.com/awslabs/aws-dataall/assets/125404584/98978e4d-4b1b-4ce0-a12f-c6abf03c2b9e)

2. In the next script, db migration script is altering the db columns devStratgey and devStage which can not be null.
  
![image](https://github.com/awslabs/aws-dataall/assets/125404584/0f64dd82-266e-4034-8665-79fd45dbf0a8)

The initial script executed without issues, but upon running the second script, an error occurred indicating that the 'devStage' column cannot have a null value. This error occurred because no default value was assigned to the column.

Error message from cloudwatch logs:

 
![image](https://github.com/awslabs/aws-dataall/assets/125404584/65f55502-4bb8-4417-9d24-e7ee60aa45b7)

### How to Reproduce

When pushing the 1.5.5 code and triggering the build process it is failing at the dataall-dev-dbmigration-stage stage.

### OS

n/a

### Python version

3.7

### AWS data.all version

1.5.5

**Comment by MATTT-P** [comment]
Thanks for getting back to me @dlpzx, if we allow null values, are there any dependencies on these values? Were they notnull by design as values from these fields are needed elsewhere?

**Comment by dlpzx** [comment]
Hi @MATTT-P, that is what I am checking at the moment. I am already able to see a couple of places in the frontend where non-null values are expected. I am going to investigate a little more option 1 to see which one is better.

**Comment by dlpzx** [comment]
Hi @MATTT-P, after checking in the code, I am most certain that updating the migration scripts looks like a better solution. I opened a [ PR](https://github.com/awslabs/aws-dataall/pull/651) for this. I still need to do some more testing on it, but you can have a look and if in a hurry give it a try on your end.

**Comment by dlpzx** [comment]
Hi @MATTT-P. I finalized the PR for the fix in the migration script, it will be reviewed and probably merged by today/Monday. You might need to do some manual steps if your migration scripts failed. Let us know if you need support on this, otherwise we can connect with your team internally

**Comment by dlpzx** [comment]
Completed!
