### ISSUE TITLE
Visibility on shared folders - link to S3 folder shared with us

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#65]
When a data.all folder (=S3 prefix) is shared with my team, we cannot access the content of the folder from the UI. Our IAM role has access to the folder, but in order to see the content of the folder we need to "trick" an URL to the S3 bucket and folder.

I would like a direct link that provided this URL with my team's (the requester) IAM role from the shared folder. This way I would have visibility on the content of the folder that has been shared with my team. We could add this access in the "Overview" tab of the shared folder:

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/71252798/175878883-205ec952-1b98-432a-96c6-175a6c8fb43e.png">

**Comment by LEUNGUU** [comment]
Is it kind of a list of files or folders in a specific S3 folders showed in the overview tab? @dlpzx

**Comment by LEUNGUU** [comment]
@dlpzx Agree with you. I think I can take this.
