### ISSUE TITLE
Data.all Administrator group name

### ISSUE THREAD

**Issue by dosiennik** [awslabs/aws-dataall#70]
Hi,

   Seems like a group name for the data.all Administrator - 'DAAdministrators' is hardcoded in a few places in the code base. It may not fit all the organisations, especially when external IdP is used.  It would be nice to make it configurable.

**Comment by dlpzx** [comment]
Hi dosiennik,

It might be useful for the case that you mentioned: an existing IdP group that works as "Tenant group" in an organisation and that can be re-used in data.all. 

From a user point of view, I would like to configure the IdP group used as Tenant, this could be specified at the time of the deployment of data.all or later if we use AWS SSM Parameter Store or Secrets Manager.
