### ISSUE TITLE
Cannot query field 'userRoleForGlossary' on type 'Glossary'

### ISSUE THREAD

**Issue by vipulra** [awslabs/aws-dataall#702]
### Describe the bug

While trying to access the glossary in new data.all version, getting an error _Cannot query field 'userRoleForGlossary' on type 'Glossary'._

<img width="580" alt="image" src="https://github.com/awslabs/aws-dataall/assets/63492410/967a12a2-2fce-4831-963f-1fbd6b80fb33">

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
Steps to reproduce:
1. Create a new glossary
2. Open the newly created glossary

### Expected behavior

GetGlossary API request should return the value for userRoleForGlossary.

### OS

Linux

### Python version

3.8

### AWS data.all version

1.5.5

**Comment by dlpzx** [comment]
Hi @vipulra thanks for opening the issue and attaching the logs. I have tried to recreate the issue in my V1.6 deployment (which is the same as V1.6 with regards to glossaries). So, I will need more info to track your problem:
- The logs look like the local development logs, is you problem happening in an AWS deployment or locally?
- Was the Glossary created before upgrading?

Let's see if we can find the issue. Welcome to the project

**Comment by vipulra** [comment]
Hi @dlpzx,

- Yes, we are encountering this issue both in our local environment and in our AWS deployment.
- We are experiencing this issue with both the glossaries that were created before the upgrade and the newly created glossary.

Do we need to update the backend/dataall/db/models/Glossary.py to make userRoleForGlossary a query expression? 
![image](https://github.com/awslabs/aws-dataall/assets/63492410/48effb4c-7f48-4de6-bcd5-9adce1bbb122)

**Comment by vipulra** [comment]
I've identified the problem, it stemmed from some custom code we had developed in an old version of data.all. 
Thank you for looking into this.

**Comment by vipulra** [comment]
I've identified the problem, it stemmed from some custom code we had developed in an old version of data.all. 
Thank you for looking into this.
