### ISSUE TITLE
Consumption Role Clarification 

### ISSUE THREAD

**Issue by vipulra** [awslabs/aws-dataall#707]
While trying to open the teams from the environment tab in data.all UI, we are getting an error pop-up **No Consumption IAM Role added
An error occurred (UnauthorizedOperation) when calling LIST_ENVIRONMENT_CONSUMPTION_ROLES operation: User: <email> is not authorized to perform: LIST_ENVIRONMENT_CONSUMPTION_ROLES on resource: <resource_id>**  

<img width="479" alt="image" src="https://github.com/awslabs/aws-dataall/assets/63492410/752f37e4-9dec-4f51-a847-769a97393504">

When we checked consumption_role table in RDS, it was blank. Also, the permission table is missing the newly added permission 
LIST_ENVIRONMENT_CONSUMPTION_ROLES and  ADD_ENVIRONMENT_CONSUMPTION_ROLES.

While calling listEnvironmentGroupInvitationPermissions API request, we are getting a null value for  ADD_ENVIRONMENT_CONSUMPTION_ROLES.

![image](https://github.com/awslabs/aws-dataall/assets/63492410/f0a26bfb-ee28-4d14-b724-3323eb42e1c1)

@dlpzx  @louishourcade

**Comment by dlpzx** [comment]
Hi @vipulra, thanks for opening an issue and the debugging info. I think you are on the right track, the  issue is on the null in the listEnvironmentGroupInvitationPermissions. Instead you should get something like:
<img width="943" alt="image" src="https://github.com/awslabs/aws-dataall/assets/71252798/b1423229-1ee4-4227-8dc9-1190fa5bcd2a">

When consumption roles were introduced, the migration script `backend/migrations/versions/04d92886fabe_add_consumption_roles.py` added the `consumption_role` table and permissions in RDS. 

In your case the table was added but the permissions weren't right?

**Comment by vipulra** [comment]
Yes, the consumptionrole table was successfully created through the migration script, but unfortunately, the corresponding permission wasn't added to the permission table.

**Comment by vipulra** [comment]
We further analyzed this issue and we found that during the db migration script to add consumption and permission failed with the below error.

<img width="524" alt="image" src="https://github.com/awslabs/aws-dataall/assets/63492410/721c1ea7-e24a-46a7-acd7-2da4d907c5a1">

There is no entry in the permission table for the consumption role, will you be able to provide the entry?

@dlpzx @louishourcade

**Comment by dlpzx** [comment]
Hi @vipulra we actually added this issue to the ones we want to triage to see if we can reproduce it. It seems that you had an issue with orphan datasets at the time of the migration. Have you advanced on this?

**Comment by vipulra** [comment]
Hi @dlpzx, Since you mentioned that you will try to reproduce this issue, were you able to reproduce it?
Let's set up a call to discuss the same as it is critical for our development.

Regarding orphan datasets, yes we were able to check in RDS.

**Comment by vipulra** [comment]
Root cause: The root cause of the issue is a mismatch in the number of permissions. The init_permissions function in the add_consumption roles migration script does not correctly add these permissions.

@dlpzx, we followed the steps you mentioned during the call, and they worked perfectly. The issue with the consumption role has been resolved. Thank you for your help.

**Comment by dlpzx** [comment]
Hi @vipulra I am very glad to hear! I was going to inform you that my tests were also successful :)
