### ISSUE TITLE
Fix permissions in Env Team permissions tat don't have business friendly names/description

### ISSUE THREAD

**Issue by manjulaK** [awslabs/aws-dataall#716]
### Describe the bug

On the environment invite team window permissions include 
LIST_ENVIRONMENT_DATASETS and LIST_ENVIRONMENT_SHARED_WITH_OBJECTS.  Note: v2.0 modularization version is the only version with this issue.

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

Add business friendly descriptions . Also put tooltips on permissions to explain in more detail what they do when they cant be explained with a short sentence

### OS

All

### Python version

3.1

### AWS data.all version

v2.0 modularization

**Comment by dlpzx** [comment]
Hi @manjulaK, thanks for raising this issue. We noticed it and fixed it in https://github.com/awslabs/aws-dataall/pull/728

**Comment by zsaltys** [comment]
@dlpzx I think we can close this then.
