### ISSUE TITLE
Enhancing Dataset representation to consider mutiple buckets & filtered list of tables

### ISSUE THREAD

**Issue by blitzmohit** [awslabs/aws-dataall#720]
**Is your feature request related to a problem? Please describe.**
We have a few databases currently in production use with 30+ tables where each of those tables point to a different S3 bucket. 

Additionally the same logical dataset could be split across multiple tables & s3 buckets, this could be done to enhance performance (there are limits to read/writes that a particular bucket/prefix can handle) or make them easier to manage.

For example a click metrics dataset with hourly table & aggregated daily table (i.e. 2 tables & 2 separate s3 buckets) and a display metrics dataset with just one table and bucket.

Currently data.all's dataset representation is based on the idea of one s3 bucket and 1 glue database with all tables in that database pointing to this bucket. 

The data as described earlier does not lend well to importing and sharing in data.all, for example which bucket out of the 30 would you specify as the dataset bucket and the complete database does not be part of the dataset only specific tables.

**Describe the solution you'd like**
When importing a database the user should be able to select or filter the list of tables being imported from a particular database & specify the list of buckets that would be imported as part of the dataset.

- Adding support for multiple buckets in a dataset and making them available as a sharable item as part of the dataset. 
- Adding support for filtering of tables that are imported as part of a dataset
- Check crawler, profiling and sharing for modifications now that a database spans multiple datasets

**Describe alternatives you've considered**
Creating a new logical construct "dataset group" which contains multiple datasets and sharing support on the level of the group, Based on the previous example click hourly & click daily would be two datasets in the click dataset group.

*P.S. Please Don't attach files. Add code snippets directly in the message body instead.*

**Comment by zsaltys** [comment]
@dlpzx @blitzmohit I think at the moment this issue is too wide and we should open separate more specific items. I propose we close this one out.

**Comment by dlpzx** [comment]
Merged and released with v2.1.0 🚀
