### ISSUE TITLE
on import prefilter database tables based on table S3 location

### ISSUE THREAD

**Issue by zsaltys** [awslabs/aws-dataall#745]
**Is your idea related to a problem? Please describe.**
A user may have 1 Glue database which has tables which point to many S3 buckets. Importing such a database into a single dataset does not make sense as potentially many of the tables will not point to the same bucket as the dataset.

**Describe the solution you'd like**
When a user imports a database which has tables which point to a buckets which are not part of a dataset then those tables are filtered out and will never show up as part of the dataset.

**Comment by zsaltys** [comment]
related to:
https://github.com/awslabs/aws-dataall/issues/720
https://github.com/awslabs/aws-dataall/issues/284

**Comment by zsaltys** [comment]
We will contribute this fix as part of https://github.com/awslabs/aws-dataall/issues/284

**Comment by dlpzx** [comment]
Hi @zsaltys thanks for opening the issue. I like the separation between the multiple-buckets datasets and the filtering imported tables. We'll keep the discussion on both #720 and here

**Comment by dlpzx** [comment]
Closing as completed
