### ISSUE TITLE
Unable to build frontend locally from Dockerfile

### ISSUE THREAD

**Issue by Jamesgo1** [awslabs/aws-dataall#753]
### Describe the bug

Hi, 

Apologies if there is something I'm doing wrong as I'm new to this project.

However, there seems to be a compatibility issue with the node version. 

I get the following error message when trying to build the frontend:

```
------
 > [frontend  8/16] RUN . ~/.nvm/nvm.sh && npm install -g npm yarn:
7.142 npm ERR! code EBADENGINE
7.143 npm ERR! engine Unsupported engine
7.144 npm ERR! engine Not compatible with your version of node/npm: npm@10.1.0
7.144 npm ERR! notsup Not compatible with your version of node/npm: npm@10.1.0
7.144 npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
7.145 npm ERR! notsup Actual:   {"npm":"8.19.4","node":"v16.20.2"}
7.147
7.147 npm ERR! A complete log of this run can be found in:
7.147 npm ERR!     /root/.npm/_logs/2023-09-13T11_04_15_698Z-debug-0.log
------
failed to solve: process "/bin/sh -c . ~/.nvm/nvm.sh && npm install -g npm yarn" did not complete successfully: exit code: 1
```

I have tried changing the node version to a later one but it seems later versions aren't supported as I get a GLIBC_2.27 not found error if I switch to node version 20.5.0 which it seems to recommend. 

### How to Reproduce

This is simply after cloning the repo and running ``` docker-compose up```

### Expected behavior

To successfully deploy locally as described [in the docs](https://awslabs.github.io/aws-dataall/deploy-locally/)

### OS

Windows

### Python version

3.9.13

### AWS data.all version

Cloned 12/09/23

**Comment by Jamesgo1** [comment]
OK thank you.  I did think it might be something wrong on my end. I'll try again and see if I can get it working.

**Comment by dlpzx** [comment]
Hi @Jamesgo1, welcome to the project! We faced the same issue last week on the AWS deployment with VPC facing frontend, it is reported and solved in this [PR](https://github.com/awslabs/aws-dataall/pull/724). This was a short-term fix, while we work on a full upgrade of node in data.all. I am not sure why you have that issue locally. My guess is that your npm version might be conflicting, check the [file changes](https://github.com/awslabs/aws-dataall/pull/724/files) for the fix. Let me know if you need any more help

**Comment by Jamesgo1** [comment]
Brilliant thanks, changing that line in frontend/docker/dev/Dockerfile fixed the issue for me.

**Comment by anmolsgandhi** [comment]
Closing this as the suggestions fixed the issue, feel free to reopen if you have any questions or need more assistance
