### ISSUE TITLE
Local deployment : user from deployment account is not authorized to perform sts:AssumeRole on dataallPivotRole in environment account

### ISSUE THREAD

**Issue by InasK6** [awslabs/aws-dataall#759]
### Describe the bug

**Context**
the` .aws/credentials` file is configured with permanent user's credentials generated from IAM user console. The user has administratorAccess
at create environment step, at get stack step the following error is received
`error:User:arn:aws:sts:dep_account:assumed-role/Admin/user-name is not authorized to perform: sts:AssumeRome on resource: arn:aws:iam:env_account:role/dataallPivotRole`

**Investigation**
The pivot role stack created generates a Trust policy containing the following condition (both from nested pivot role stack and pivotRole.yaml file present in deploy folder):
`"StringLike": {
                    "aws:PrincipalArn": [
                        "arn:aws:iam::account_number:role/*graphql-role",
                        "arn:aws:iam::account_number:role/*awsworker-role",
                        "arn:aws:iam::account_number:role/*ecs-tasks-role"
                    ]`

**Temporary solution**
The temporary solution I used to work around this issue was to delete the previous condition from my **trust policy** . 

**Further work**
How to guarantee **least privilege principle** while enabling the local evironment to use the pivot role having user credentials ?

1. Should we enforce a specific naming convention for the users and add it as part of the previous condition ?
2. Is this condition with String comparison really strong ? anyone can juste create a role and name it in a way that the respects that convention i.e.  I can create a role and name it inas-graphql-role even if what the role performs is not graphql api requests etc ...

I would be happy to contribute to solving this issue

### Expected behavior

credentials used locally allow to assume pivotRole to perform actions on data.all locally

### OS

macos

### Python version

3.9.6

### AWS data.all version

v1.6.0

**Comment by dlpzx** [comment]
Hi @InasK6! Yes, we added that hardening of the pivot roles as part of a security review. Your guesses are totally right, the trust policy prevents any role assumption expect for those suffixed.
1. For local development you can create a role called `local-graphql-role` or any that satisfies this naming convention
2. The only permissions that this role needs are assume role permissions to pivotRoles. It is a role that is only used to assume the pivot role, then it is the pivot role the one that executes the SDK calls

**Comment by InasK6** [comment]
thank you for the clarification @dlpzx
