### ISSUE TITLE
CDK-nag actions from external forks do not have write permissions

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#766]
### Describe the bug

As happens in this PR, the cdk-nag action requires write permissions, but the maximum permissions allowed for a fork in a public repo are `read` permissions.
![image](https://github.com/awslabs/aws-dataall/assets/71252798/c276830e-6068-4c4e-a9da-87f8cc522bc3)

**alternatives**
1. use [ok-to-test](https://github.com/imjohnbo/ok-to-test) --> requires authentication, preferred is GitHub App (not possible for data.all),  other options: personal access token or OAuth app token
2. run cdk-nag action only on minor release branches (v2m2m0 to main) branch
3. run cdk-nag on `pull_request_target` after the PR is merged
4. run cdk-nag on schedule
5. Use other than OIDC
6. running without credentials --> maybe mocking the cdk.context.json, not adding fake values but mocking it

Advice:
6 woudl solve the issue, so preferred if possible. 2 and 3 can also be added.

### How to Reproduce
Open a PR from a fork.

### OS

n/a

### Python version

n/a

### AWS data.all version

7.0.0

**Comment by anmolsgandhi** [comment]
Hi @dlpzx This is marked as high priority and in progress, if you are working on it id like to add it to v2.1.0 milestone to track it.

**Comment by dlpzx** [comment]
Completed in #767
