### ISSUE TITLE
Security Hub flags up "CodeBuild.5 CodeBuild project environments should not have privileged mode enabled" for data.all CDK Master pipeline

### ISSUE THREAD

**Issue by idpdevops** [awslabs/aws-dataall#776]
Security Hub flags up a HIGH severity issue "CodeBuild.5 CodeBuild project environments should not have privileged mode enabled" for the data.all CDK Master pipeline. This finding is part of aws-foundational-security-best-practices/v/1.0.0

It would be great if the data.all CDK Master pipeline CodeBuild project could be updated to be compliant.

Reference: https://docs.aws.amazon.com/securityhub/latest/userguide/codebuild-controls.html#codebuild-5

**Comment by anmolsgandhi** [comment]
Thank @noah-paige for your response. @idpdevops Closing this issue, if you still have concerns or need further assistance, please dont hesitate to reopen the issue, we're here to help!
