### ISSUE TITLE
Glossary Limitations for terms and categories

### ISSUE THREAD

**Issue by GenyaKan** [awslabs/aws-dataall#79]
### Describe the bug

I tried to create a new glossary which supposed to have 3 category and 13 terms. at some point while i was creating the terms and categories it started to overwrite or delete existing once. on the glossary dashboard it looks like glossary has 8 categories and 13 terms but if you click on glossary you can see only 3 category (one has no terms) and two other has some terms but it is less terms that I entered for this category. So it looks like I have 1 category with 3 terms and 2 categories with 3 terms each. My third category was supposed to have 4 terms and did so till i added the other term

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Screenshots

![image](https://user-images.githubusercontent.com/108880601/177789148-06ec2b8c-53f1-4952-8293-4ff1d0027666.png)
![image](https://user-images.githubusercontent.com/108880601/177789328-88c870bb-38d1-4b02-9eaf-1772d1e00c07.png)

### OS

Linux

### Python version

NA

### AWS data.all version

NA

**Comment by louishourcade** [comment]
Hello Genya,
Thanks for submitting this issue. If I try to summarize you face the following issues:
* Inconsistency between what you see on the dashboard with what you see in the glossary overview (might be due to the deletion / edition of some resources)
* In the Glossary overview, you cannot see some terms that you added previously

Is that correct ?

**Comment by dlpzx** [comment]
Hi Genyakan,

I was able to recreate your issue. There is indeed an inconsistency and some categories and terms being deleted from the detailed view of the glossary. I will add this bug to the project to be fixed. Thank you for raising the issue

**Comment by louishourcade** [comment]
Hi Genya,
I created a PR to fix this issue. It was just related to a limit in the number of items shown in the frontend. I increased it.
Best
