### ISSUE TITLE
Allow for bring-your-own VPC for SageMaker domains

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#795]
**Is your feature request related to a problem? Please describe.**
Our customer has restricted networking requirements. Actions such as creation of internet gateways are forbidden with SCPs (Service Control Policies). When we try to link an environment with MLStudio enabled, and having no default VPCs, data.all tries to create a VPC for the SageMaker domain. This action fails as it is blocked by the SCPs.

**Describe the solution you'd like**
I want an alternative way of providing VPCs for the environment SageMaker domain.

**Describe alternatives you've considered**
- One option would be to add the bring-your-own VPC id as an optional input for the environment creation

**Additional context**

*P.S. Please Don't attach files. Add code snippets directly in the message body instead.*

**Comment by lorchda** [comment]
Please also update architecture diagrams to show missing components that the solution is creating (VPC, IGW and so on).

**Comment by lorchda** [comment]
data.all is looking for a [default VPC](https://github.com/awslabs/aws-dataall/blob/6e2fdb0a05ec36e1ecda205875280f44bf57d03a/backend/dataall/modules/mlstudio/cdk/mlstudio_extension.py#L45), and in the absence of such a default VPC, it creates its own network resources.

This assumes the presence of a default VPC. This logic needs to be reviewed. The [default VPC](https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html) is a resource with spezialised properties (CIDR ranges and so on), that might not be compatible with the customer environment, and thus the creation of this resource cannot be easily accomodated.

In the absence of a default VPC, could the _existing_ VPC in the AWS account be used?

**Comment by lorchda** [comment]
Thank you both!
