### ISSUE TITLE
Editable Environment Parameters with All Modules Disabled

### ISSUE THREAD

**Issue by noah-paige** [awslabs/aws-dataall#807]
### Describe the bug

When any (or all) of the modules are disabled - the relative environment parameters show up with their toggle switches when you go to edit the environment.

Functionality wise there seems to be no impact (i.e. even if ML Studio parameter turned on when editing with ML Studio module disabled - No Studio Domain is created) but it is confusing to the user

### How to Reproduce

* Disable one of the following modules that map to environment parameters
    * MLStudio, notebooks, dashboards, or pipelines

* Deploy Data.all
* Go to an existing environment or create a new one - on edit of the environment can still see the environment parameter of the disabled module

### Expected behavior

Environment parameter that maps to a specific module should not be present on the UI if the module is disabled

### OS

N/A

### Python version

N/A

### AWS data.all version

v2.0

**Comment by dlpzx** [comment]
Merged and released with v2.1.0 🚀
