### ISSUE TITLE
DBT data.all pipelines

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#85]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

*P.S. Please Don't attach files. Add code snippets directly in the message body instead.*

**Comment by anmolsgandhi** [comment]
We will be focused on maturing the data.all pipelines play functionality before introducing DBT or other similar constructs. Feel free to reopen the issue if its still a priority requirement
