### ISSUE TITLE
Uncaught exception for SCP-related AccessDeniedException in QuickSight DescribeGroup operation in us-east-1

### ISSUE THREAD

**Issue by lorchda** [awslabs/aws-dataall#851]
### Describe the bug

When trying to start a QuickSight session, the following error is displayed:

```
An error occurred (AccessDeniedException) when calling the DescribeGroup operation:
User:arn:aws:sts:REDACTED:assumed-role/REDACTED is not authorized to perform: quicksight:DescribeGroup
on resource: am:aws:quicksight.us-east-1:REDACTED:group/default/dataall with an explicit deny in a service
control policy
```

### How to Reproduce

The call trace is as follows:
1. User clicks on "Start a QuickSight Session"
2. data.all frontend issues GraphQL operation `GetAuthorSession`
3. data.all backend handles `get_identity_region`, which uses hardcoded parameter `us-east-1` in [backend/dataall/base/aws/quicksight.py#L40](https://github.com/awslabs/aws-dataall/blob/df14146ce1e33f6ad38bfd2d94c38a576b8a2330/backend/dataall/base/aws/quicksight.py#L40)
4. The [exception block](https://github.com/awslabs/aws-dataall/blob/df14146ce1e33f6ad38bfd2d94c38a576b8a2330/backend/dataall/base/aws/quicksight.py#L46) catches `AccessDeniedException`, but does not foresee exceptions due to service control policies

We were able to temporarily fix the issue by changing the value from `us-east-1` to `eu-central-1` (but thereby changing the logic of the function).

A more correct fix would be to review the block in `except client.exceptions.AccessDeniedException as e:`,  ensure the `explicit deny in a service control policy` is caught with a fall back to the user's local region for `identity_region`.

### Expected behavior

We are able to Start a QuickSight Session without errors.

### data.all

<img width="628" alt="1-quicksight-error" src="https://github.com/awslabs/aws-dataall/assets/98748454/98de8915-f4a4-44f3-8d10-c0ef8af3df4b">

### Developer Tools: Request

<img width="825" alt="2-devtools-request" src="https://github.com/awslabs/aws-dataall/assets/98748454/087f3bf7-79d3-4934-8230-e700d8aeaa71">

### Developer Tools: Response

<img width="857" alt="3-devtools-response" src="https://github.com/awslabs/aws-dataall/assets/98748454/0f7f5729-c2ab-4a12-9720-ae1a765014a2">

### CloudWatch Logs for GraphQL Lambda

<img width="1431" alt="4-cwlogs" src="https://github.com/awslabs/aws-dataall/assets/98748454/ef120f37-c5c8-4b71-8ec6-cfea0925c08b">

### OS

Windows

### Python version

python3.8

### AWS data.all version

v2.0.0

**Comment by dlpzx** [comment]
Hi @lorchda, we are facing similar issues when registering users. We defaulted the identity region to the default when subscribing to Quicksight, but as more regions are added as identity regions it seems like there is a need to resolve the identity region in a better way. Let us discuss this feature internally but we will look into it. 

I'll leave here some resources related to this issue ([1](https://community.amazonquicksight.com/t/identity-region-sin-ap-southeast-1-and-some-region-questions/17134), [2](https://community.amazonquicksight.com/t/we-are-getting-an-access-denied-exception-saying-our-operation-is-being-called-on-us-east-2-but-our-identity-region-is-us-east-1-but-as-far-as-we-can-tell-our-quicksight-setup-is-for-us-east-2/5819))

**Comment by dlpzx** [comment]
We will iterate only through the Quicksight identity regions available
![image](https://github.com/awslabs/aws-dataall/assets/71252798/32b4b477-acc2-41c3-a984-049fdd88400d)
