### ISSUE TITLE
KMS CMK key is not being rotated

### ISSUE THREAD

**Issue by zsaltys** [awslabs/aws-dataall#879]
We are using a KMS CMK key which is not being rotated and is picked up by Checkov scanner:

```
CheckID		: CKV_AWS_7
CheckName	: Ensure rotation for customer created CMKs is enabled
File		: /cdk.out/dataall-cdk-template-cicd-stack.template.json:1755-1819
Resource	: AWS::KMS::Key.dataallcdktemplatecdkpipelinePipelineArtifactsBucketEncryptionKeyDCDBA3C9
Guideline	: CKV_AWS_7 
```

All KMS CMK keys should be rotated as a best security practice.

**Comment by noah-paige** [comment]
I believe this is in reference to the CodePipeline created in `dataall/deploy/stacks/pipeline.py` file. We need to test if adding the `enable_key_rotation=True` parameter to the CodePipeline would cause any unforeseen issues but should be easy to implement and align with best practices

Should be good to pick this up shortly barring any capacity setbacks, thank @zsaltys

**Comment by dlpzx** [comment]
Completed in #923
