### ISSUE TITLE
Re-auth modal gets overriden by the delete modal

### ISSUE THREAD

**Issue by zsaltys** [awslabs/aws-dataall#917]
### Describe the bug

When trying to delete a dataset re-auth pops and then gets overriden by the delete modal...

### How to Reproduce

Delete a dataset and have re-auth pop...

### Expected behavior

Re-auth modal should always be on top... 

### Screenshots

![overlays](https://github.com/awslabs/aws-dataall/assets/1583403/1a623e2a-d1e0-44e6-b7d9-c0abb0b959c7)

### OS

N/A

### Python version

N/A

### AWS data.all version

2.0

**Comment by zsaltys** [comment]
@noah-paige fyi

**Comment by noah-paige** [comment]
Thanks for filing the issue @zsaltys - was able to replicate the above behavior and identify the root cause

Have a fix in this [PR](https://github.com/awslabs/aws-dataall/pull/914/files)

**Comment by zsaltys** [comment]
@noah-paige thank you!
