### ISSUE TITLE
Frontend role creation error out on Cloudformation when switching from Cognito to Custom Auth

### ISSUE THREAD

**Issue by TejasRGitHub** [awslabs/aws-dataall#937]
### Describe the bug

When using data.all v2.2 , `{resource_prefix}-{envname}-frontend-config-role` is created inside the IdpStack ( Cognito Nested Stack ). During switching from Cognito Auth to Custom Auth, the cloudformtation template ( generated by cdk) tries to create the same role in backend stack before deleting the role in the same role in the IdpStack ( Cognito Nested Stack ) 

Error on Cloudformation : `dataall-staging-frontend-config-role already exists in stack arn:aws:cloudformation:<REGION>:<AWS_ACCOUNT>:stack/dataall-staging-backend-stage-backend-stack-CognitoNestedStackCognitoNestedStackResour-/18700...`

### How to Reproduce

1. Install Data.all with Cognito Auth 
2. Switch to Custom Auth Provider by adding the `custom_auth` configs as mentioned here https://github.com/awslabs/aws-dataall/blob/main/template_cdk.json

### Expected behavior

Because cloud formation tries to create resources before it deletes them, this role should not be created again while switching from cognito to custom auth . 

Possible Solution - 
Create Cognito Role (`{resource_prefix}-{envname}-cognito-config-role`) in the IdpStack() as before and use this role in the ALBFrontend and while configuring cognito 
When using custom-auth, use the other role  `{resource_prefix}-{envname}-frontend-config-role` to create frontend configs files for deploying with ALBFrontend stage. 

### OS

Mac

### Python version

3.9

### AWS data.all version

2.2

**Comment by dlpzx** [comment]
Discussion happening directly in linked PR

**Comment by dlpzx** [comment]
Closing as PR is merged
