### ISSUE TITLE
fix local instructions?

### ISSUE THREAD

**Issue by cfregly** [awslabs/aws-dataall#94]
### Describe the bug

<img width="694" alt="image" src="https://user-images.githubusercontent.com/1438064/180045370-0c7862f2-658a-4819-9206-3898e29228d2.png">

### How to Reproduce

instructions

### Screenshots

<img width="694" alt="image" src="https://user-images.githubusercontent.com/1438064/180045435-b95ab492-3eaf-430f-adef-fcc9bf9194c1.png">

### OS

mac

### Python version

3.9

### AWS data.all version

latest

**Comment by dlpzx** [comment]
Hi @cfregly , can you describe the bug in more detail?

**Comment by gavclark-arriva** [comment]
The local deployment instructions may contain a typo. The directory mentioned (data.all) doesn't exist when deployed locally - perhaps it is meant to be aws-dataall ? . 

When I ran docker compose up within the aws-dataall directory, it worked fine.

**Comment by dlpzx** [comment]
Fixed, thank you
